export type BucketOption = { mark: number; text: string };

export type BucketQuestion = {
  id: string;
  question: string;
  navigate: string;
  options: BucketOption[];
};

export const QUESTION_BANK: Record<string, BucketQuestion[]> = {
  'Navigation & Findability': [
    { id:'N01', question:'Is the primary navigation structure clear and easy to understand?', navigate:'Open the homepage or main entry screen. Look at the navigation without interacting. Note whether structure is immediately obvious to a first-time visitor.', options:[{mark:1,text:'Unclear or confusing — users cannot orient themselves at all'},{mark:2,text:'Understandable but significantly confusing — major rework needed'},{mark:3,text:'Understandable but slightly confusing — some improvements needed'},{mark:4,text:'Clear with minor gaps — mostly intuitive for new users'},{mark:5,text:'Clear and intuitive — users orient immediately without any confusion'}] },
    { id:'N02', question:'Are navigation labels descriptive and meaningful?', navigate:'Read every label in the main nav, sidebar, and any secondary menus. Compare each label against plain-language alternatives.', options:[{mark:1,text:'Vague, generic, or misleading — labels do not match user expectations'},{mark:2,text:'Mostly vague — 3 or more labels are unclear or use internal terminology'},{mark:3,text:'Partially clear — 1 or 2 labels are inconsistent or ambiguous'},{mark:4,text:'Mostly clear — labels are descriptive with minor inconsistencies'},{mark:5,text:'Clear and self-explanatory — all labels match user mental models perfectly'}] },
    { id:'N03', question:'Can users easily find key pages or features?', navigate:'Attempt to find 3 key features or pages without using search. Navigate only using menus. Count attempts needed for each.', options:[{mark:1,text:'Difficult to find or hidden — key features require significant searching'},{mark:2,text:'Findable with considerable effort — most users would struggle'},{mark:3,text:'Discoverable with some effort — minor friction or unexpected paths'},{mark:4,text:'Easily discoverable with minimal effort — most features found quickly'},{mark:5,text:'Immediately discoverable — all key features found without any searching'}] },
    { id:'N04', question:'Is it clear where the user is within the site or app?', navigate:'Navigate to 5 different screens. On each, check for breadcrumbs, active nav states, highlighted menu items, or page titles indicating current location.', options:[{mark:1,text:'Often unclear — no breadcrumbs, active states, or location indicators anywhere'},{mark:2,text:'Rarely clear — location indicated only on 1 or 2 screens'},{mark:3,text:'Sometimes clear — location indicators present but inconsistent'},{mark:4,text:'Usually clear — indicators present on most screens with minor gaps'},{mark:5,text:'Always clear — breadcrumbs, active states, and context indicators on every screen'}] },
    { id:'N05', question:'Is navigation behaviour consistent across the product?', navigate:'Interact with the same navigation component on 5 different screens. Check whether behaviour is identical each time.', options:[{mark:1,text:'Frequently inconsistent — navigation behaves differently on many screens'},{mark:2,text:'Often inconsistent — same patterns behave differently in multiple places'},{mark:3,text:'Minor inconsistencies — 2 or 3 screens where navigation behaves unexpectedly'},{mark:4,text:'Mostly consistent — one minor inconsistency found'},{mark:5,text:'Fully consistent — same navigation patterns behave identically everywhere'}] },
    { id:'N06', question:'Does the navigation structure scale with content complexity?', navigate:'Count all items in the primary navigation. Check whether the structure handles current volume without feeling cluttered.', options:[{mark:1,text:'Breaks down or feels overwhelming — navigation cannot handle current content volume'},{mark:2,text:'Heavily strained — navigation is cluttered and hard to use'},{mark:3,text:'Works but feels strained — minor clutter or crowding visible'},{mark:4,text:'Scales reasonably well — minor structural improvements would help'},{mark:5,text:'Scales well and remains usable — navigation adapts cleanly to content volume'}] },
    { id:'N07', question:'Are alternate navigation paths available when needed?', navigate:'Look for search functionality, secondary menus, in-page anchor links, and keyboard shortcuts. Test each one that exists.', options:[{mark:1,text:'Missing or ineffective — no secondary navigation, search, or shortcuts anywhere'},{mark:2,text:'Very limited — only one alternative path and it is hard to find'},{mark:3,text:'Available but limited — search or secondary links present but incomplete'},{mark:4,text:'Available and mostly useful — secondary paths work but could be better'},{mark:5,text:'Clearly available and useful — search, secondary menus, shortcuts all present'}] },
    { id:'N08', question:'Can the user reach the core action in 3 clicks or fewer from the homepage?', navigate:'Start from the homepage. Navigate to the most important action. Count every click.', options:[{mark:1,text:'Requires 7 or more clicks — core action is effectively buried'},{mark:2,text:'Requires 5 to 6 clicks — significant navigation depth'},{mark:3,text:'Requires 4 clicks — one more step than ideal'},{mark:4,text:'Requires 3 clicks — acceptable with minor friction'},{mark:5,text:'Reached in 1 to 2 clicks — immediately accessible from entry screen'}] },
    { id:'N09', question:'Is the back navigation predictable and reliable?', navigate:'Navigate deep into the product then use the back button. Check whether the result is what is expected.', options:[{mark:1,text:'Back navigation is broken or absent — users get stuck or lose progress'},{mark:2,text:'Back navigation works but loses user data or resets state unexpectedly'},{mark:3,text:'Back navigation works but redirects to unexpected screens occasionally'},{mark:4,text:'Back navigation works reliably with one minor unexpected behaviour'},{mark:5,text:'Back navigation is fully predictable — works correctly in every flow'}] },
    { id:'N10', question:'Are key user flows friction-free with no dead ends or broken links?', navigate:'Navigate every flow listed in the audit scope from start to finish. Note every broken link, dead end, or unexpected redirect.', options:[{mark:1,text:'Multiple dead ends, broken links, or failed flows found across the product'},{mark:2,text:'2 or 3 significant friction points or broken steps found'},{mark:3,text:'1 friction point found — one step in a flow that causes confusion'},{mark:4,text:'Flows are mostly smooth with very minor friction in one place'},{mark:5,text:'All flows complete seamlessly — no dead ends, broken links, or unexpected stops'}] }
  ],
  'Content & UX Writing': [
    { id:'W01', question:'Does the homepage headline communicate what the product does, who it is for, and why it matters?', navigate:'Load the homepage. Read only the headline and subheadline — do not scroll. Check whether what, who, and why are all addressed.', options:[{mark:1,text:'Vague or generic — headline says nothing specific about the product'},{mark:2,text:'States what the product does but audience and value are completely missing'},{mark:3,text:'States what and who but why it matters requires scrolling to understand'},{mark:4,text:'Communicates all three but one element is slightly unclear'},{mark:5,text:'All three elements clear in the hero — no scrolling required to understand'}] },
    { id:'W02', question:'Are CTA button labels outcome-oriented and specific?', navigate:'Read every CTA button across the homepage, core feature screen, and conversion screen. Classify each as outcome-oriented or generic.', options:[{mark:1,text:'All CTAs are generic — Submit, Click here, Go, or Learn more throughout'},{mark:2,text:'Most CTAs are generic — only 1 or 2 are specific across the product'},{mark:3,text:'Mix of specific and generic — approximately half are outcome-oriented'},{mark:4,text:'Most CTAs are specific — 1 generic CTA found on a secondary screen'},{mark:5,text:'All CTAs describe the outcome — every button tells the user what happens next'}] },
    { id:'W03', question:'Is terminology consistent across all screens?', navigate:'Navigate 6 screens and note what key features and actions are called on each. Look for the same concept being named differently.', options:[{mark:1,text:'Same features called completely different names on different screens'},{mark:2,text:'3 or more terminology inconsistencies found across the product'},{mark:3,text:'1 or 2 inconsistencies — same feature referred to differently in places'},{mark:4,text:'Mostly consistent with one minor terminology variation'},{mark:5,text:'Fully consistent — same words used for same things everywhere throughout'}] },
    { id:'W04', question:'Are error messages written in plain language with a specific actionable fix?', navigate:'Trigger at least 3 errors — submit an empty required form, enter invalid credentials, attempt an unauthorised action. Read every error message.', options:[{mark:1,text:'Technical error codes or completely generic errors — no fix provided'},{mark:2,text:'Errors show what went wrong but the fix is completely absent'},{mark:3,text:'Errors state the problem in plain language but the fix is vague'},{mark:4,text:'Errors are clear and mostly actionable with minor improvements needed'},{mark:5,text:'All errors are plain language with specific problem and specific fix stated'}] },
    { id:'W05', question:'Is helper text, microcopy, or tooltips present at key decision points?', navigate:'Navigate to the most complex form, the onboarding flow, and the checkout or upgrade flow. Look for helper text, tooltips, placeholder guidance, and inline hints.', options:[{mark:1,text:'No microcopy anywhere — users are left to guess throughout the entire product'},{mark:2,text:'Microcopy present in only 1 place — all other decision points have no guidance'},{mark:3,text:'Present at some decision points but missing at the most critical ones'},{mark:4,text:'Present at most decision points with one or two gaps'},{mark:5,text:'Guidance present at every key decision point throughout the product'}] },
    { id:'W06', question:'Is content structured for scanning with headings, short paragraphs, and emphasis?', navigate:'Open any content-heavy screen. Check whether content is skimmable without reading every word.', options:[{mark:1,text:'Wall of text throughout — no headings, no structure, no visual emphasis'},{mark:2,text:'Very little structure — long paragraphs with minimal formatting'},{mark:3,text:'Some structure present — headings exist but large text blocks remain'},{mark:4,text:'Mostly scannable — minor areas where long text blocks appear'},{mark:5,text:'Fully scannable — headings, short paragraphs, and clear emphasis throughout'}] },
    { id:'W07', question:'Are success and confirmation messages specific with next steps indicated?', navigate:'Complete 3 different primary actions. Read the confirmation message that appears after each action.', options:[{mark:1,text:'No confirmation messages — users have no idea if their action succeeded'},{mark:2,text:'Generic silent state change only — action appears to complete but nothing is said'},{mark:3,text:'Generic confirmation shown — Done or Success with no next step'},{mark:4,text:'Specific confirmation present but next step is not indicated'},{mark:5,text:'Specific confirmation with clear next step on every completed action'}] },
    { id:'W08', question:'Is all copy free of jargon, filler phrases, and redundant text?', navigate:'Read all copy on 4 key screens. Count instances of jargon, buzzwords, filler phrases, and redundant repetition.', options:[{mark:1,text:'Heavy jargon and buzzwords throughout — inaccessible to non-expert users'},{mark:2,text:'Significant jargon present — multiple screens have inaccessible copy'},{mark:3,text:'Some jargon present — 3 or more instances across the product'},{mark:4,text:'Mostly clear — 1 or 2 instances of jargon or unnecessary filler'},{mark:5,text:'No jargon or filler — every word is necessary and plain throughout'}] },
    { id:'W09', question:'Is the value proposition communicated consistently across all key screens?', navigate:'Read the core message on the homepage, a feature page, and the pricing or upgrade screen. Check whether the same positioning is consistently communicated.', options:[{mark:1,text:'No consistent value proposition — each screen communicates something different'},{mark:2,text:'Value proposition only on homepage — completely absent on other screens'},{mark:3,text:'Present on 2 screens but inconsistent or contradictory in places'},{mark:4,text:'Consistent on most screens — one screen feels off-message'},{mark:5,text:'Same clear positioning consistently communicated on every key screen'}] },
    { id:'W10', question:'Does microcopy guide users through complex workflows and multi-step processes?', navigate:'Navigate the longest multi-step flow in the product. Check for guidance at every step.', options:[{mark:1,text:'No guidance in any workflow — users must figure out every step alone'},{mark:2,text:'Guidance appears only at the first step — subsequent steps have no help'},{mark:3,text:'Guidance at entry and exit only — middle steps have no microcopy'},{mark:4,text:'Guidance at most steps — one critical mid-flow step lacks explanation'},{mark:5,text:'Comprehensive microcopy at every step of every complex workflow'}] }
  ],
  'Visual Hierarchy & Layout': [
    { id:'V01', question:'Is there a clear visual focal point on each key screen?', navigate:'Load homepage, core feature screen, and conversion screen. On each, note the very first element attention is drawn to.', options:[{mark:1,text:'No focal point — attention is completely scattered across competing elements'},{mark:2,text:'Focal point exists but 3 or more elements compete equally with it'},{mark:3,text:'Focal point present but 1 or 2 elements distract from it significantly'},{mark:4,text:'Focal point is clear with one minor competing element present'},{mark:5,text:'One dominant focal point on every screen — eye goes there immediately'}] },
    { id:'V02', question:'Is there a clear information hierarchy from most to least important?', navigate:'Check any 3 screens. Compare visual weight of primary actions, secondary content, and supporting text.', options:[{mark:1,text:'No hierarchy — everything appears at the same visual weight'},{mark:2,text:'Very weak hierarchy — primary and secondary content look almost identical'},{mark:3,text:'2-level hierarchy only — primary is distinct but secondary and tertiary are the same'},{mark:4,text:'3-level hierarchy present but tertiary elements could be more subdued'},{mark:5,text:'Clear 3+ level hierarchy — primary, secondary, and tertiary are all visually distinct'}] },
    { id:'V03', question:'Is spacing used consistently to organise and group content?', navigate:'Inspect spacing on 3 screens — between sections, form fields, and cards. Compare margin and padding consistency.', options:[{mark:1,text:'Random or no spacing — elements appear scattered with no visual logic'},{mark:2,text:'Inconsistent spacing — major differences in margins and padding across screens'},{mark:3,text:'Some consistent spacing — 3 or more areas where spacing feels random'},{mark:4,text:'Mostly consistent — 1 area where spacing feels inconsistent'},{mark:5,text:'Fully consistent spacing throughout — clear grouping and separation everywhere'}] },
    { id:'V04', question:'Is the primary CTA visible above the fold on mobile without scrolling?', navigate:'Set viewport to 375px. Load homepage and primary conversion screen. Check whether main CTA is visible without scrolling.', options:[{mark:1,text:'CTA not visible above fold on either desktop or mobile'},{mark:2,text:'CTA visible on desktop but requires significant scrolling on mobile'},{mark:3,text:'CTA visible on desktop but requires one scroll on mobile'},{mark:4,text:'CTA visible above fold on both but slightly small or not prominent enough'},{mark:5,text:'CTA prominently visible above fold on both desktop and mobile'}] },
    { id:'V05', question:'Does the typography establish a clear visual hierarchy?', navigate:'Open any content-heavy screen. Identify heading levels H1 through H3, body text, labels, and captions.', options:[{mark:1,text:'All text appears the same size and weight — no typographic hierarchy at all'},{mark:2,text:'Only 2 levels — headings and body text — subheadings and labels look identical'},{mark:3,text:'2 clear levels with partial differentiation of a third level'},{mark:4,text:'3 clear typographic levels with one minor inconsistency'},{mark:5,text:'4+ clear typographic levels — immediately scannable throughout the product'}] },
    { id:'V06', question:'Is visual noise minimised with no distracting elements competing with the primary action?', navigate:'Scan 3 screens for decorative elements, competing banners, or repeated CTAs that distract from the primary action.', options:[{mark:1,text:'Heavy visual noise — multiple banners and competing CTAs clutter every screen'},{mark:2,text:'Significant noise on most screens — primary action is regularly obscured'},{mark:3,text:'Noise present on 2 or 3 screens — distracting from the primary action'},{mark:4,text:'Mostly clean — one minor distracting element on one screen'},{mark:5,text:'No visual noise — every element serves a purpose and primary action is unobstructed'}] },
    { id:'V07', question:'Does the layout adapt correctly across desktop, tablet, and mobile breakpoints?', navigate:'Test the primary flow at 1280px desktop, 768px tablet, and 375px mobile. Check for overflow, broken layouts, or cut-off content.', options:[{mark:1,text:'Layout is completely broken on mobile — horizontal scroll and overlapping elements'},{mark:2,text:'Significant layout issues on mobile — unusable on small screens'},{mark:3,text:'Minor layout issues on one breakpoint — small element or spacing problem'},{mark:4,text:'Layout mostly adapts — one minor reflow issue on tablet or mobile'},{mark:5,text:'Perfect reflow at all breakpoints — no layout issues at any screen size'}] },
    { id:'V08', question:'Are related elements visually grouped using proximity, borders, or background?', navigate:'Check any form, feature section, or content block. Verify that related elements are grouped by proximity or visual cues.', options:[{mark:1,text:'No grouping — all elements appear scattered across the screen with no visual logic'},{mark:2,text:'Very weak grouping — most related elements are not visually connected'},{mark:3,text:'Some grouping — 2 or 3 content sections where related elements are not grouped'},{mark:4,text:'Mostly grouped — one section where related elements are slightly scattered'},{mark:5,text:'All related elements clearly grouped — proximity and visual cues used throughout'}] },
    { id:'V09', question:'Is the layout guiding the eye flow from headline through content to the CTA?', navigate:'On the homepage and conversion screen, trace the visual path from the headline down the page toward the primary CTA.', options:[{mark:1,text:'Eye flow is completely random — no logical sequence from entry to CTA'},{mark:2,text:'Eye flow breaks significantly at the midpoint — does not lead to CTA'},{mark:3,text:'Eye flow is mostly logical but breaks once before reaching the CTA'},{mark:4,text:'Eye flow leads to CTA but one element slightly disrupts the path'},{mark:5,text:'Eye flows naturally from headline through content directly to CTA on every screen'}] },
    { id:'V10', question:'Is visual weight balanced with no non-primary element accidentally dominating the screen?', navigate:'Check 3 screens for any element that dominates unintentionally — large background image, bright secondary badge, or oversized secondary CTA.', options:[{mark:1,text:'Multiple non-primary elements dominate — primary action is visually lost'},{mark:2,text:'One non-primary element dominates most screens accidentally'},{mark:3,text:'One screen where a secondary element accidentally competes with the primary'},{mark:4,text:'Balance is mostly correct — one minor element slightly heavier than intended'},{mark:5,text:'Perfectly balanced — primary elements dominate intentionally on every screen'}] }
  ],
  'Accessibility & Inclusivity': [
    { id:'A01', question:'Does all body text meet WCAG 2.1 AA contrast ratio of 4.5:1?', navigate:'Check contrast of body text, labels, placeholder text, and disabled states on homepage, form screen, and core feature screen.', options:[{mark:1,text:'Multiple contrast failures across several screens — body text fails throughout'},{mark:2,text:'3 or more contrast failures found across key screens'},{mark:3,text:'1 or 2 contrast failures found — muted text or disabled state text fails'},{mark:4,text:'All text passes except one low-priority muted text element'},{mark:5,text:'All text passes 4.5:1 on every screen — fully WCAG 2.1 AA compliant'}] },
    { id:'A02', question:'Can a keyboard-only user navigate and operate the full primary flow without a mouse?', navigate:'Use the Tab key only to navigate the complete primary flow. Press Enter or Space to activate elements.', options:[{mark:1,text:'Keyboard navigation is completely broken — primary flow cannot be completed'},{mark:2,text:'Keyboard navigation works for less than half the primary flow'},{mark:3,text:'Keyboard navigation works for most of the flow but 2 elements are unreachable'},{mark:4,text:'Keyboard navigation works throughout with one minor focus trap or skip'},{mark:5,text:'Full keyboard navigation works perfectly — entire primary flow operable without mouse'}] },
    { id:'A03', question:'Are focus states visible on all interactive elements when tabbing through the page?', navigate:'Tab through any full page. Observe whether each focusable element shows a visible focus ring or highlight.', options:[{mark:1,text:'No visible focus states anywhere — keyboard users cannot track their position'},{mark:2,text:'Focus states present on less than half of interactive elements'},{mark:3,text:'Focus states present on most elements but missing on several links or inputs'},{mark:4,text:'Focus states present on almost all elements — missing on one secondary component'},{mark:5,text:'Visible focus state on every interactive element — clearly distinguishable throughout'}] },
    { id:'A04', question:'Do all form fields have persistent visible labels — not just placeholder text?', navigate:'Navigate to any form. Click into each field and begin typing. Check whether the label remains visible above or beside the field.', options:[{mark:1,text:'All fields use placeholder text only — all labels disappear on typing'},{mark:2,text:'Most fields use placeholder only — fewer than 2 have persistent labels'},{mark:3,text:'Mix of persistent labels and placeholder-only fields across the form'},{mark:4,text:'Most fields have persistent labels — one field uses placeholder text only'},{mark:5,text:'All fields have persistent visible labels — no labels disappear when typing begins'}] },
    { id:'A05', question:'Are all tap and click targets at least 44 x 44 pixels on mobile?', navigate:'Set viewport to 375px. Visually inspect all interactive elements — buttons, icon buttons, navigation links, toggles, and checkboxes.', options:[{mark:1,text:'Most targets are below 44px — buttons, icons, and links are all too small on mobile'},{mark:2,text:'Multiple targets below 44px — icon buttons and navigation links are too small'},{mark:3,text:'2 or 3 targets below 44px — mostly icon buttons or close buttons'},{mark:4,text:'1 target slightly below 44px — a minor icon or secondary link'},{mark:5,text:'All tap and click targets meet or exceed 44px on mobile — fully accessible'}] },
    { id:'A06', question:'Are errors and status indicators communicated through more than just colour?', navigate:'Trigger a form error. Observe the error indicator. Check whether it uses only colour or also includes an icon or text label.', options:[{mark:1,text:'Errors communicated through colour only — no icon, pattern, or label added'},{mark:2,text:'Most error indicators are colour-only — text label present in only one case'},{mark:3,text:'Some errors use colour plus text — others use colour only'},{mark:4,text:'Most errors use colour plus icon — one error uses colour only'},{mark:5,text:'All errors use colour plus icon plus text label — three independent signals'}] },
    { id:'A07', question:'Does the layout remain usable and readable when browser zoom is set to 200%?', navigate:'Set browser zoom to 200% on the homepage and core feature screen. Check for horizontal scroll, overlapping elements, or cut-off content.', options:[{mark:1,text:'Layout completely breaks at 200% — horizontal scroll and overlapping content'},{mark:2,text:'Significant layout issues at 200% — content is cut off on multiple screens'},{mark:3,text:'Minor layout issue at 200% — one element slightly cut off or overlapping'},{mark:4,text:'Mostly usable at 200% — one small spacing issue found'},{mark:5,text:'Fully usable at 200% zoom — no horizontal scroll or overlapping elements'}] },
    { id:'A08', question:'Are images and meaningful visual elements accompanied by descriptive alt text?', navigate:'Inspect the HTML of images on 3 key screens. Check whether meaningful images have descriptive alt text.', options:[{mark:1,text:'No alt text on any images — all are completely inaccessible to screen readers'},{mark:2,text:'Alt text present on fewer than half of meaningful images'},{mark:3,text:'Alt text present on most images — 2 or 3 meaningful images are missing it'},{mark:4,text:'Almost all images have alt text — one meaningful image is missing it'},{mark:5,text:'All meaningful images have descriptive alt text — decorative images have empty alt'}] },
    { id:'A09', question:'Is animation and motion controlled and non-disruptive?', navigate:'Observe all animations and transitions. Enable OS reduced-motion setting and reload to check whether animations are suppressed.', options:[{mark:1,text:'Heavy animation throughout — no reduced-motion support and some elements flash'},{mark:2,text:'Significant animation with no reduced-motion support at all'},{mark:3,text:'Animation present with partial reduced-motion support — some animations persist'},{mark:4,text:'Animation is subtle with mostly correct reduced-motion support'},{mark:5,text:'Animations are subtle, respect reduced-motion preference, and no elements flash'}] },
    { id:'A10', question:'Is all content understandable at a broad reading level without expert knowledge?', navigate:'Read the copy on the homepage, onboarding flow, and error messages as if you are a non-expert user.', options:[{mark:1,text:'Heavy jargon and technical language throughout — inaccessible to general users'},{mark:2,text:'Significant technical language — non-expert users would struggle on most screens'},{mark:3,text:'Some technical language on 2 or 3 screens — partially inaccessible'},{mark:4,text:'Mostly accessible — one area where language is slightly technical'},{mark:5,text:'Plain language throughout — accessible to users of all literacy levels'}] }
  ],
  'Input, Errors & Validation': [
    { id:'E01', question:'Do form fields communicate format requirements before the user submits?', navigate:'Navigate to any form with specific format requirements. Check whether constraints are visible before submission.', options:[{mark:1,text:'No format requirements shown — users discover constraints only by failing'},{mark:2,text:'Requirements shown on only 1 field — all others have no upfront guidance'},{mark:3,text:'Requirements shown on some fields — others revealed only after errors'},{mark:4,text:'Most fields show requirements upfront — one field reveals only after error'},{mark:5,text:'All format requirements shown upfront before submission on every field'}] },
    { id:'E02', question:'Is validation performed in real time as the user types or on leaving a field?', navigate:'Fill in a form field with invalid data and move to the next field without submitting. Check whether inline validation appears immediately.', options:[{mark:1,text:'Validation only after full form submission — no real-time feedback at all'},{mark:2,text:'Validation present on one field only — all others validate only on submit'},{mark:3,text:'Validation on some fields — others only validate on submission'},{mark:4,text:'Real-time validation on most fields — one field validates only on submit'},{mark:5,text:'Real-time inline validation on all fields — errors appear immediately on blur'}] },
    { id:'E03', question:'Are error messages shown inline next to the specific field that needs fixing?', navigate:'Submit any form with empty required fields. Observe exactly where the error message appears.', options:[{mark:1,text:'Generic error at top only — no field is highlighted or indicated'},{mark:2,text:'Error at top of form only — user must guess which field caused the error'},{mark:3,text:'Error shown at top but correct field is also highlighted'},{mark:4,text:'Inline error on the correct field — message could be more specific'},{mark:5,text:'Inline error on specific field with clear plain language actionable fix'}] },
    { id:'E04', question:'Is the user input preserved when a form error occurs?', navigate:'Fill a form with valid and invalid data mixed. Submit. Check whether all previously entered valid data is still present after the error.', options:[{mark:1,text:'All fields are cleared on error — user must retype everything from scratch'},{mark:2,text:'Most fields are cleared — only 1 field retains its value on error'},{mark:3,text:'Some fields preserved — approximately half are cleared on error'},{mark:4,text:'Most input preserved — one field unexpectedly clears on error'},{mark:5,text:'All previously valid input preserved — only the erroneous field is flagged'}] },
    { id:'E05', question:'Are destructive actions protected by a confirmation step before executing?', navigate:'Find and attempt every destructive action in the product. Note whether each one shows a confirmation before executing.', options:[{mark:1,text:'Destructive actions execute immediately with no warning or confirmation step'},{mark:2,text:'Confirmation present on one destructive action — others execute immediately'},{mark:3,text:'Confirmation on some but missing on at least one destructive action'},{mark:4,text:'Confirmation on most destructive actions — one minor action lacks it'},{mark:5,text:'Confirmation step present on every single destructive action in the product'}] },
    { id:'E06', question:'Can users correct mistakes without losing progress or restarting the flow?', navigate:'Reach the final step of a multi-step flow. Use the back button to change an earlier answer. Check whether all subsequent progress is preserved.', options:[{mark:1,text:'Correcting any mistake destroys all progress — user must restart completely'},{mark:2,text:'Going back loses most progress — only the last step can be changed'},{mark:3,text:'Going back loses some progress — 2 or more subsequent steps reset'},{mark:4,text:'Going back mostly preserves progress — one step resets unexpectedly'},{mark:5,text:'Users can go back and correct any step without losing any progress'}] },
    { id:'E07', question:'Does the 404 page provide navigation back to a useful destination?', navigate:'Enter a non-existent URL on the product domain. Read the 404 page. Check whether it has navigation links or a clear link back.', options:[{mark:1,text:'Generic server error or blank page — no navigation or explanation at all'},{mark:2,text:'Default 404 page with no helpful links or navigation options'},{mark:3,text:'Basic 404 with a homepage link only — no search or helpful content'},{mark:4,text:'Custom 404 with navigation links but copy is generic or unhelpful'},{mark:5,text:'Custom 404 with navigation links, helpful copy, and a clear next step'}] },
    { id:'E08', question:'Are complex tasks broken into steps with visible progress indication?', navigate:'Navigate any multi-step flow. Check whether steps are numbered, labelled, and whether a progress bar or step counter is shown.', options:[{mark:1,text:'No step indication anywhere — users cannot tell where they are in any flow'},{mark:2,text:'Multi-step flows present with no numbering, labels, or progress indication'},{mark:3,text:'Steps numbered but no progress bar or completion percentage shown'},{mark:4,text:'Steps numbered with labels — progress bar missing on one flow'},{mark:5,text:'All multi-step flows have numbered steps, labels, and a progress bar'}] },
    { id:'E09', question:'Does the system proactively prevent common mistakes through input constraints?', navigate:'Test input fields that have specific constraints — phone numbers, dates, credit cards. Check whether the interface prevents incorrect input.', options:[{mark:1,text:'No proactive prevention — users can enter anything and only learn on submit'},{mark:2,text:'Very minimal prevention — only 1 field has any form of input constraint'},{mark:3,text:'Some prevention in place — most error types can still be entered freely'},{mark:4,text:'Good prevention on most fields — one field allows incorrect format input'},{mark:5,text:'Input masking, hints, and constraints actively prevent incorrect input everywhere'}] },
    { id:'E10', question:'Are helpful default values pre-filled in form fields to reduce user effort?', navigate:'Navigate to any form where defaults could reasonably apply. Check whether sensible defaults are pre-selected or pre-filled.', options:[{mark:1,text:'No defaults anywhere — every field starts completely blank'},{mark:2,text:'Defaults present on only 1 field where several obvious defaults exist'},{mark:3,text:'Some defaults present — half of fields where defaults apply have them'},{mark:4,text:'Most sensible defaults pre-filled — one obvious default is missing'},{mark:5,text:'All sensible defaults pre-filled wherever appropriate — minimising user effort'}] }
  ],
  'Feedback & System States': [
    { id:'F01', question:'Does the user receive a clear confirmation after completing a primary action?', navigate:'Complete the primary action in the product. Observe the immediate visual response — toast, success screen, confirmation banner, or state change.', options:[{mark:1,text:'No confirmation at all — interface does not change after any action'},{mark:2,text:'Silent state change only — action appears to complete but nothing is said'},{mark:3,text:'Generic confirmation only — Done or Success with no context or next step'},{mark:4,text:'Specific confirmation present but next step is not indicated'},{mark:5,text:'Specific confirmation with next step clearly indicated on every primary action'}] },
    { id:'F02', question:'Is a loading indicator shown whenever data is loading or processing?', navigate:'Navigate between pages and trigger several data-loading actions. Check whether a spinner, skeleton, or progress bar appears every time.', options:[{mark:1,text:'Screen freezes or goes completely blank during loading — no indicator shown'},{mark:2,text:'Loading indicator shown on less than half of loading events'},{mark:3,text:'Loading indicator present but inconsistent — missing on 2 or 3 events'},{mark:4,text:'Loading indicator shown on most events — missing on one minor loading state'},{mark:5,text:'Loading indicator shown every time without exception — spinner or skeleton always present'}] },
    { id:'F03', question:'Does an empty state guide the user toward an action rather than showing a blank screen?', navigate:'Log in with a fresh account or navigate to an empty list or dashboard. Observe the empty state design.', options:[{mark:1,text:'Completely blank screen — no text, no CTA, no illustration, no guidance'},{mark:2,text:'Text explains the empty state but provides no action or guidance'},{mark:3,text:'Explanation present with a CTA but the guidance is vague'},{mark:4,text:'Good empty state with explanation and CTA — illustration would improve it'},{mark:5,text:'Guided empty state with explanation, clear CTA, and visual direction'}] },
    { id:'F04', question:'Does the submit button change state immediately to prevent double submission?', navigate:'Click any primary submit or payment button. Observe the button within half a second of clicking.', options:[{mark:1,text:'Button stays fully active during processing — can be clicked multiple times'},{mark:2,text:'Button remains active for 2 or more seconds before changing state'},{mark:3,text:'Button changes state but with noticeable delay that allows a second click'},{mark:4,text:'Button changes state quickly — a very narrow window for double-click exists'},{mark:5,text:'Button disables or shows spinner immediately on click — double submission impossible'}] },
    { id:'F05', question:'Are active states visible on navigation, tabs, and selected elements?', navigate:'Navigate to 4 different sections. Check the navigation for active state indicators. Toggle switches and select tabs.', options:[{mark:1,text:'No visible active states anywhere — users cannot tell what is selected'},{mark:2,text:'Active states present on navigation only — tabs and toggles show no state'},{mark:3,text:'Active states on some components — missing on at least 2 interactive elements'},{mark:4,text:'Active states on most components — missing on one secondary element'},{mark:5,text:'Active state clearly visible on every interactive element throughout the product'}] },
    { id:'F06', question:'Are success moments positively reinforced at key milestones?', navigate:'Complete the onboarding flow, reach the aha moment, and complete a primary task for the first time. Observe whether these moments are acknowledged.', options:[{mark:1,text:'Success moments are completely silent — nothing marks any achievement'},{mark:2,text:'Primary actions complete silently — only one minor moment is acknowledged'},{mark:3,text:'Some success moments acknowledged with plain confirmation — no delight'},{mark:4,text:'Most success moments acknowledged — one milestone is not reinforced'},{mark:5,text:'Success moments celebrated with appropriate animation, copy, or visual reward'}] },
    { id:'F07', question:'Does the system communicate proactively when background processes complete?', navigate:'Trigger any background process — auto-save, sync, export, or refresh. Check whether the user is notified when it completes.', options:[{mark:1,text:'No proactive communication — users must manually check or refresh to see results'},{mark:2,text:'Notification exists for one background process only — all others are silent'},{mark:3,text:'Some processes communicate completion — others require manual checking'},{mark:4,text:'Most background processes notify the user — one is silent'},{mark:5,text:'Users always notified when any background process completes'}] },
    { id:'F08', question:'Are stressful or high-stakes interactions softened with reassuring design?', navigate:'Navigate to the highest-stakes interaction — account deletion, payment, or irreversible action. Check for reassuring copy, visible cancel, and undo options.', options:[{mark:1,text:'High-stakes actions are abrupt — no reassurance, no cancel, and no undo option'},{mark:2,text:'Cancel is present but no reassuring copy and no undo option'},{mark:3,text:'Cancel and basic reassurance present — no undo for irreversible actions'},{mark:4,text:'Cancel, reassurance, and undo mostly present — one element could be improved'},{mark:5,text:'Reassuring copy, visible cancel, and undo all present on every high-stakes screen'}] },
    { id:'F09', question:'Do interactive elements provide immediate visual feedback on hover and click?', navigate:'Hover over and click 10 different interactive elements across the product. Check for visual change on hover and a distinct response on click.', options:[{mark:1,text:'No hover states or click feedback on any interactive element'},{mark:2,text:'Hover states on buttons only — links and icons have no feedback'},{mark:3,text:'Hover feedback on most elements — click feedback missing on 2 or 3 elements'},{mark:4,text:'Hover and click feedback on most elements — one element has no feedback'},{mark:5,text:'All interactive elements respond immediately to hover and click throughout'}] },
    { id:'F10', question:'Does the interface communicate errors when the system fails or goes offline?', navigate:'Simulate a network error or trigger a session timeout. Read the error message shown.', options:[{mark:1,text:'Blank screen or generic server error — no explanation and no recovery path'},{mark:2,text:'Error is shown but it is a technical code or completely vague'},{mark:3,text:'Plain language error shown but no recovery action provided'},{mark:4,text:'Error with recovery action — copy could be more specific or reassuring'},{mark:5,text:'Plain language explanation plus specific recovery action on every system error'}] }
  ],
  'Consistency & UI Patterns': [
    { id:'C01', question:'Do all primary buttons look identical across every screen of the product?', navigate:'Navigate 6 screens. Note the colour, size, border radius, and font weight of every primary button. Compare all instances.', options:[{mark:1,text:'Multiple completely different button styles used for primary actions'},{mark:2,text:'3 or more different primary button styles found across the product'},{mark:3,text:'2 different primary button styles used — one consistent, one exception'},{mark:4,text:'Fully consistent with one minor deviation on a secondary screen'},{mark:5,text:'All primary buttons identical — same colour, size, radius, and weight everywhere'}] },
    { id:'C02', question:'Does the same interaction always produce the same result throughout the product?', navigate:'Find a repeated UI pattern — cards, tags, list rows, or action icons. Interact with the same pattern in 3 different contexts.', options:[{mark:1,text:'Same UI elements do completely different things in different places'},{mark:2,text:'Same pattern behaves differently in 3 or more contexts'},{mark:3,text:'Same pattern behaves differently in 2 contexts'},{mark:4,text:'Same pattern behaves differently in one context — one unexpected variation'},{mark:5,text:'Same interaction produces same result in every context — fully predictable'}] },
    { id:'C03', question:'Do all screens feel like they belong to the same product visually?', navigate:'Navigate to 6 screens including settings, error screen, and secondary flow screens. Compare visual language across all.', options:[{mark:1,text:'Multiple screens look like they belong to completely different products'},{mark:2,text:'Several screens — 3 or more — have visually distinct styles'},{mark:3,text:'2 screens feel visually different from the main product style'},{mark:4,text:'1 screen feels slightly different — a secondary flow or settings screen'},{mark:5,text:'All screens feel cohesive and unified — unmistakably one product throughout'}] },
    { id:'C04', question:'Are icons always accompanied by text labels?', navigate:'Check every icon-based navigation item, action button, and status indicator. Note every icon used without a visible text label.', options:[{mark:1,text:'Multiple ambiguous action icons used with no text labels throughout'},{mark:2,text:'Most icons lack labels — only 1 or 2 have accompanying text'},{mark:3,text:'Some icons have labels — others do not — inconsistent approach'},{mark:4,text:'Most icons have labels — only universal icons used without labels'},{mark:5,text:'All icons have text labels — no icon is used without context or explanation'}] },
    { id:'C05', question:'Are all interactive states designed — hover, active, disabled, loading, and focus?', navigate:'Hover, click, tab through, and find disabled versions of buttons, links, inputs, and cards. Check whether each state is visually distinct.', options:[{mark:1,text:'Only default state designed — all other states look identical to default'},{mark:2,text:'Default and hover states only — disabled, loading, and focus are missing'},{mark:3,text:'Default, hover, and active states — disabled and focus states missing'},{mark:4,text:'4 of 5 states designed — one state missing across some components'},{mark:5,text:'All 5 states designed and visually distinct for every interactive element'}] },
    { id:'C06', question:'Are components reused systematically rather than rebuilt custom for each screen?', navigate:'Compare cards, tables, modals, and form inputs across 4 different screens. Check whether the same component is reused or rebuilt each time.', options:[{mark:1,text:'Every screen has its own custom components — no systematic reuse at all'},{mark:2,text:'Minimal reuse — only 1 or 2 components are shared across screens'},{mark:3,text:'Partial reuse — major components shared but several screens have custom rebuilds'},{mark:4,text:'Good reuse — mostly systematic with one or two custom one-off components'},{mark:5,text:'Fully systematic reuse — same components used consistently across every screen'}] },
    { id:'C07', question:'Does the product follow established platform conventions?', navigate:'Test these conventions — click outside a modal to dismiss, press Escape to close overlays, click the logo to return home, use browser back button.', options:[{mark:1,text:'Multiple platform conventions broken — product behaves against user expectations'},{mark:2,text:'3 or more conventions broken — users regularly encounter unexpected behaviour'},{mark:3,text:'2 conventions broken — back button, modal dismiss, or link behaviour unexpected'},{mark:4,text:'1 minor convention broken — mostly follows expected platform behaviour'},{mark:5,text:'All platform conventions followed — product behaves exactly as users expect'}] },
    { id:'C08', question:'Is styling uniform — same typeface, colour palette, and border radius throughout?', navigate:'Check typography, colour usage, border radius, and icon style across 6 screens. Flag any deviation from the homepage style.', options:[{mark:1,text:'Multiple different typefaces, colour palettes, and styles used across screens'},{mark:2,text:'3 or more styling inconsistencies found — font, colour, or radius deviations'},{mark:3,text:'2 styling inconsistencies — one screen uses a different font or colour'},{mark:4,text:'1 minor styling deviation — one secondary screen has a small inconsistency'},{mark:5,text:'Fully uniform styling — zero visual deviations on any screen'}] },
    { id:'C09', question:'Does the experience feel cohesive from the first screen to the deepest feature?', navigate:'Navigate the full primary flow from entry to the deepest feature screen. Evaluate whether the design language remains consistent throughout.', options:[{mark:1,text:'Experience feels fragmented — different sections feel designed by completely different teams'},{mark:2,text:'Significant fragmentation — 3 or more sections feel noticeably disconnected'},{mark:3,text:'One major section feels noticeably different from the rest of the product'},{mark:4,text:'Mostly cohesive — one minor section slightly disconnects from the overall experience'},{mark:5,text:'Fully cohesive end-to-end — same design language from entry to deepest feature'}] },
    { id:'C10', question:'Is there evidence of a design system being applied systematically?', navigate:'Look for systematic use of spacing scales, colour tokens, type scales, and component patterns across 5+ screens.', options:[{mark:1,text:'No evidence of a design system — everything appears custom and inconsistent'},{mark:2,text:'Very minimal system — spacing or colour appears inconsistently applied'},{mark:3,text:'Partial system — some patterns are systematic but many are ad-hoc'},{mark:4,text:'Good system evidence — minor deviations suggest it is not fully enforced'},{mark:5,text:'Clear evidence of a mature design system applied consistently throughout'}] }
  ],
  'code optimisation': [
    { id:'P01', question:'How fast does the product largest visible element load on a standard mobile connection?', navigate:'Open browser DevTools, set network throttle to Fast 3G or Slow 4G, load the homepage. Check the LCP value in the Performance tab.', options:[{mark:1,text:'LCP exceeds 6 seconds on mobile — severely slow and users will abandon'},{mark:2,text:'LCP between 4 and 6 seconds — significantly slower than acceptable'},{mark:3,text:'LCP between 2.5 and 4 seconds — below Google Core Web Vitals threshold'},{mark:4,text:'LCP between 1.5 and 2.5 seconds — meets threshold with room to improve'},{mark:5,text:'LCP under 1.5 seconds on mobile — excellent performance throughout'}] },
    { id:'P02', question:'Is there significant layout shift while the page loads?', navigate:'Load the homepage and core feature screen. Watch whether elements shift position after the initial render.', options:[{mark:1,text:'CLS score above 0.25 — major layout instability, elements jump noticeably'},{mark:2,text:'CLS between 0.15 and 0.25 — significant layout shift on most screens'},{mark:3,text:'CLS between 0.1 and 0.15 — fails Core Web Vitals threshold'},{mark:4,text:'CLS between 0.05 and 0.1 — minor instability, close to passing'},{mark:5,text:'CLS below 0.05 — no visible layout shift, fully stable loading experience'}] },
    { id:'P03', question:'How quickly does the product respond to the first user interaction?', navigate:'Open Lighthouse or Chrome DevTools Performance panel. Load the page and measure the time from first click or tap to visible response.', options:[{mark:1,text:'FID or INP above 500ms — interaction feels completely broken and frozen'},{mark:2,text:'FID or INP between 200ms and 500ms — noticeably sluggish on every interaction'},{mark:3,text:'FID or INP between 100ms and 200ms — fails Core Web Vitals threshold'},{mark:4,text:'FID or INP between 50ms and 100ms — meets threshold with room to improve'},{mark:5,text:'FID or INP below 50ms — interactions feel instant and responsive'}] },
    { id:'P04', question:'Are images optimised — using modern formats and appropriate compression?', navigate:'Open the Network tab in DevTools. Filter by Img. Check the format and file size of the 5 largest images loaded on the homepage and core screens.', options:[{mark:1,text:'All images are unoptimised JPEG or PNG with no compression — very large file sizes'},{mark:2,text:'Most images are unoptimised — only a few are compressed or sized correctly'},{mark:3,text:'Some images optimised — approximately half use modern formats or compression'},{mark:4,text:'Most images optimised — 1 or 2 still using older formats or uncompressed'},{mark:5,text:'All images use modern formats such as WebP or AVIF with correct compression'}] },
    { id:'P05', question:'Is render-blocking JavaScript and CSS eliminated or deferred?', navigate:'Run Lighthouse on the homepage. Check the Eliminate render-blocking resources audit. Count how many scripts and stylesheets are flagged.', options:[{mark:1,text:'Multiple render-blocking resources — page cannot begin rendering until all load'},{mark:2,text:'3 or more render-blocking scripts or stylesheets found'},{mark:3,text:'2 render-blocking resources — one script and one stylesheet block rendering'},{mark:4,text:'1 minor render-blocking resource — mostly deferred correctly'},{mark:5,text:'No render-blocking resources — all scripts deferred and critical CSS inlined'}] },
    { id:'P06', question:'Are semantic HTML elements used correctly throughout the product?', navigate:'Inspect the HTML source of the homepage and core feature screen. Check whether nav, main, section, article, header, footer, h1-h6, button, and a elements are used correctly.', options:[{mark:1,text:'No semantic HTML — everything built with divs and spans only'},{mark:2,text:'Very minimal semantic HTML — headings exist but nav, main, section are absent'},{mark:3,text:'Partial semantic HTML — headings and main landmarks present but incomplete'},{mark:4,text:'Good semantic structure with one or two elements using wrong semantic role'},{mark:5,text:'Full semantic HTML — nav, main, section, article, header, footer all used correctly'}] },
    { id:'P07', question:'Are ARIA roles and labels present where native semantics are insufficient?', navigate:'Inspect the HTML of any custom components — dropdown menus, modals, carousels, tabs, and accordions. Check whether ARIA roles and labels are used correctly.', options:[{mark:1,text:'No ARIA attributes used — custom components are completely inaccessible'},{mark:2,text:'Very minimal ARIA — present on one component but absent on all others'},{mark:3,text:'Some ARIA present — major custom components lack roles or labels'},{mark:4,text:'Good ARIA coverage — one custom component missing a role or label'},{mark:5,text:'ARIA roles and labels correctly applied to all custom and complex components'}] },
    { id:'P08', question:'Are there any console errors or JavaScript exceptions on key screens?', navigate:'Open browser DevTools console. Navigate through the homepage, core feature screen, and primary flow. Note every error, warning, or exception.', options:[{mark:1,text:'Multiple critical JavaScript errors throwing on every key screen'},{mark:2,text:'2 or more JavaScript errors on key screens — functionality may be broken'},{mark:3,text:'1 JavaScript error on a key screen — non-critical but should be fixed'},{mark:4,text:'Console warnings present but no actual errors on key screens'},{mark:5,text:'Zero console errors or warnings on any key screen — clean execution'}] },
    { id:'P09', question:'Does the product work correctly without JavaScript enabled?', navigate:'Disable JavaScript in browser DevTools settings. Reload the homepage and attempt to navigate the core flow.', options:[{mark:1,text:'Product is completely broken without JavaScript — blank screen or nothing works'},{mark:2,text:'Most functionality broken without JavaScript — only static text is visible'},{mark:3,text:'Core navigation works but interactive features all fail without JavaScript'},{mark:4,text:'Most core features work — one feature requires JavaScript to function'},{mark:5,text:'Product is fully functional or degrades gracefully without JavaScript'}] },
    { id:'P10', question:'Are HTTP requests, assets, and third-party scripts minimised and optimised?', navigate:'Open the Network tab in DevTools. Load the homepage and count the total number of requests. Identify any third-party scripts that are not essential.', options:[{mark:1,text:'Excessive HTTP requests and multiple heavy third-party scripts loaded on every page'},{mark:2,text:'High number of requests — 3 or more unnecessary third-party scripts found'},{mark:3,text:'Some unnecessary requests — 1 or 2 third-party scripts not essential to the page'},{mark:4,text:'Requests mostly optimised — one minor unnecessary asset loading found'},{mark:5,text:'HTTP requests are minimal — only essential assets and scripts loaded on each page'}] }
  ]
};

export const QUESTION_BANK_VERSION = "2026-06-24";

const NEW_BUCKET_ALIASES: Array<[string, string]> = [
  ["Visual Feedback", "Feedback & System States"],
  ["Color & Contrast", "Accessibility & Inclusivity"],
  ["Typography & Readability", "Visual Hierarchy & Layout"],
  ["Keyboard Navigation", "Input, Errors & Validation"],
  ["Screen Reader Support", "Accessibility & Inclusivity"],
  ["Content (Impact)", "Content & UX Writing"],
  ["Performance", "code optimisation"],
  ["Visual Consistency", "Visual Hierarchy & Layout"],
  ["Motion & Microinteractions", "Feedback & System States"],
  ["Content (Delight)", "Content & UX Writing"],
  ["Brand Expression", "Visual Hierarchy & Layout"],
  ["Icons & Imagery", "Accessibility & Inclusivity"],
];

for (const [target, source] of NEW_BUCKET_ALIASES) {
  QUESTION_BANK[target] = QUESTION_BANK[source] || [];
}

export function getSelectedBucketQuestions(bucketNames: string[]) {
  return bucketNames.reduce<Record<string, BucketQuestion[]>>((acc, bucketName) => {
    const questions = QUESTION_BANK[bucketName];
    if (questions?.length) acc[bucketName] = questions;
    return acc;
  }, {});
}
