export type BucketOption = { mark: number; text: string };

export type BucketQuestion = {
  id: string;
  question: string;
  navigate: string;
  options: BucketOption[];
};

function scaleOptions(): BucketOption[] {
  return [
    { mark: 1, text: 'Missing or severe issues — this requirement is not met' },
    { mark: 2, text: 'Major issues — large gaps or significant friction remain' },
    { mark: 3, text: 'Partially met — usable but inconsistent or incomplete' },
    { mark: 4, text: 'Mostly meets — only minor gaps remain' },
    { mark: 5, text: 'Fully meets — clear, strong, and well supported' },
  ];
}

export const QUESTION_BANK: Record<string, BucketQuestion[]> = {
  'Visual Feedback': [
    {
      id: 'VF01',
      question: "Loading States: Is feedback shown immediately after an action starts?",
      navigate: "Review the Loading States evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF02',
      question: "Loading States: Does the loading state clearly indicate that the system is working?",
      navigate: "Review the Loading States evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF03',
      question: "Loading States: Does it prevent users from submitting the same action multiple times?",
      navigate: "Review the Loading States evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF04',
      question: "Loading States: Is the loading status communicated to assistive technologies?",
      navigate: "Review the Loading States evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF05',
      question: "Empty States: Does the empty state explain why no content is available?",
      navigate: "Review the Empty States evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF06',
      question: "Empty States: Does it provide a relevant next action?",
      navigate: "Review the Empty States evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF07',
      question: "Empty States: Does it avoid leaving users with a blank or confusing screen?",
      navigate: "Review the Empty States evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF08',
      question: "Success States: Does the interface clearly confirm that the action was completed?",
      navigate: "Review the Success States evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF09',
      question: "Success States: Does it explain what was successfully completed?",
      navigate: "Review the Success States evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF10',
      question: "Success States: Does it communicate whether any further action is required?",
      navigate: "Review the Success States evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF11',
      question: "Success States: Is the success message announced to screen-reader users?",
      navigate: "Review the Success States evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF12',
      question: "Progress Indicators: Can users understand their current position in a process?",
      navigate: "Review the Progress Indicators evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF13',
      question: "Progress Indicators: Are completed steps clearly identified?",
      navigate: "Review the Progress Indicators evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF14',
      question: "Progress Indicators: Are the remaining steps or remaining progress visible?",
      navigate: "Review the Progress Indicators evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF15',
      question: "Progress Indicators: Is progress communicated both visually and programmatically?",
      navigate: "Review the Progress Indicators evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF16',
      question: "Hover States: Do interactive elements provide a clear hover state?",
      navigate: "Review the Hover States evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF17',
      question: "Hover States: Is hover avoided as the only way to discover functionality?",
      navigate: "Review the Hover States evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF18',
      question: "Hover States: Is hover-triggered information also available through keyboard focus?",
      navigate: "Review the Hover States evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF19',
      question: "Selected States: Can users clearly distinguish selected and unselected items?",
      navigate: "Review the Selected States evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF20',
      question: "Selected States: Is selection communicated using more than colour alone?",
      navigate: "Review the Selected States evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF21',
      question: "Selected States: Is the selected state communicated programmatically?",
      navigate: "Review the Selected States evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF22',
      question: "Active States: Does the element visibly respond when clicked, tapped or pressed?",
      navigate: "Review the Active States evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF23',
      question: "Active States: Can users distinguish the active state from hover, focus, selected and disabled states?",
      navigate: "Review the Active States evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF24',
      question: "Error States: Does the interface clearly identify the exact error?",
      navigate: "Review the Error States evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF25',
      question: "Error States: Does it explain why the error occurred?",
      navigate: "Review the Error States evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF26',
      question: "Error States: Does it tell users how to correct the error?",
      navigate: "Review the Error States evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF27',
      question: "Error States: Is the error communicated using text or an icon in addition to colour?",
      navigate: "Review the Error States evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF28',
      question: "Error States: Is the error announced to screen-reader users?",
      navigate: "Review the Error States evidence within Visual Feedback.",
      options: scaleOptions(),
    },
  ],
  'Color & Contrast': [
    {
      id: 'CC01',
      question: "Contrast Ratio: Does normal text meet a minimum contrast ratio of 4.5:1?",
      navigate: "Review the Contrast Ratio evidence within Color & Contrast.",
      options: scaleOptions(),
    },
    {
      id: 'CC02',
      question: "Contrast Ratio: Does large text meet a minimum contrast ratio of 3:1?",
      navigate: "Review the Contrast Ratio evidence within Color & Contrast.",
      options: scaleOptions(),
    },
    {
      id: 'CC03',
      question: "Contrast Ratio: Do meaningful interface components meet a minimum contrast ratio of 3:1?",
      navigate: "Review the Contrast Ratio evidence within Color & Contrast.",
      options: scaleOptions(),
    },
    {
      id: 'CC04',
      question: "Contrast Ratio: Do focus indicators have sufficient contrast against adjacent colours?",
      navigate: "Review the Contrast Ratio evidence within Color & Contrast.",
      options: scaleOptions(),
    },
    {
      id: 'CC05',
      question: "Contrast Ratio: Is contrast maintained across default, hover, selected, disabled and error states?",
      navigate: "Review the Contrast Ratio evidence within Color & Contrast.",
      options: scaleOptions(),
    },
    {
      id: 'CC06',
      question: "Colour Accessibility: Can important content be distinguished under colour-vision-deficiency simulations?",
      navigate: "Review the Colour Accessibility evidence within Color & Contrast.",
      options: scaleOptions(),
    },
    {
      id: 'CC07',
      question: "Colour Accessibility: Are foreground and background combinations readable?",
      navigate: "Review the Colour Accessibility evidence within Color & Contrast.",
      options: scaleOptions(),
    },
    {
      id: 'CC08',
      question: "Colour Accessibility: Are status colours visually distinguishable?",
      navigate: "Review the Colour Accessibility evidence within Color & Contrast.",
      options: scaleOptions(),
    },
    {
      id: 'CC09',
      question: "Colour Accessibility: Are colours used consistently throughout the product?",
      navigate: "Review the Colour Accessibility evidence within Color & Contrast.",
      options: scaleOptions(),
    },
    {
      id: 'CC10',
      question: "Do Not Rely on Colour Alone: Are errors supported by text, icons or labels?",
      navigate: "Review the Do Not Rely on Colour Alone evidence within Color & Contrast.",
      options: scaleOptions(),
    },
    {
      id: 'CC11',
      question: "Do Not Rely on Colour Alone: Are success states supported by text or icons?",
      navigate: "Review the Do Not Rely on Colour Alone evidence within Color & Contrast.",
      options: scaleOptions(),
    },
    {
      id: 'CC12',
      question: "Do Not Rely on Colour Alone: Are selected states communicated through more than colour?",
      navigate: "Review the Do Not Rely on Colour Alone evidence within Color & Contrast.",
      options: scaleOptions(),
    },
    {
      id: 'CC13',
      question: "Do Not Rely on Colour Alone: Are required fields identified without relying only on colour?",
      navigate: "Review the Do Not Rely on Colour Alone evidence within Color & Contrast.",
      options: scaleOptions(),
    },
    {
      id: 'CC14',
      question: "Do Not Rely on Colour Alone: Do charts use labels, patterns, shapes or legends in addition to colour?",
      navigate: "Review the Do Not Rely on Colour Alone evidence within Color & Contrast.",
      options: scaleOptions(),
    },
  ],
  'Typography & Readability': [
    {
      id: 'TR01',
      question: "Font Size: Is body text comfortably readable on desktop?",
      navigate: "Review the Font Size evidence within Typography & Readability.",
      options: scaleOptions(),
    },
    {
      id: 'TR02',
      question: "Font Size: Is body text comfortably readable on mobile?",
      navigate: "Review the Font Size evidence within Typography & Readability.",
      options: scaleOptions(),
    },
    {
      id: 'TR03',
      question: "Font Size: Can users zoom text to 200% without losing content?",
      navigate: "Review the Font Size evidence within Typography & Readability.",
      options: scaleOptions(),
    },
    {
      id: 'TR04',
      question: "Font Size: Does zooming avoid clipping, overlapping or hidden content?",
      navigate: "Review the Font Size evidence within Typography & Readability.",
      options: scaleOptions(),
    },
    {
      id: 'TR05',
      question: "Line Height: Is there sufficient vertical spacing between lines?",
      navigate: "Review the Line Height evidence within Typography & Readability.",
      options: scaleOptions(),
    },
    {
      id: 'TR06',
      question: "Line Height: Can users comfortably scan paragraphs?",
      navigate: "Review the Line Height evidence within Typography & Readability.",
      options: scaleOptions(),
    },
    {
      id: 'TR07',
      question: "Line Height: Does the interface remain usable when line spacing is increased?",
      navigate: "Review the Line Height evidence within Typography & Readability.",
      options: scaleOptions(),
    },
    {
      id: 'TR08',
      question: "Line Height: Does it remain usable when letter, word and paragraph spacing are increased?",
      navigate: "Review the Line Height evidence within Typography & Readability.",
      options: scaleOptions(),
    },
    {
      id: 'TR09',
      question: "Readability: Are sentences clear and concise?",
      navigate: "Review the Readability evidence within Typography & Readability.",
      options: scaleOptions(),
    },
    {
      id: 'TR10',
      question: "Readability: Is familiar and simple language used?",
      navigate: "Review the Readability evidence within Typography & Readability.",
      options: scaleOptions(),
    },
    {
      id: 'TR11',
      question: "Readability: Are paragraphs easy to scan?",
      navigate: "Review the Readability evidence within Typography & Readability.",
      options: scaleOptions(),
    },
    {
      id: 'TR12',
      question: "Readability: Is unnecessary jargon avoided?",
      navigate: "Review the Readability evidence within Typography & Readability.",
      options: scaleOptions(),
    },
    {
      id: 'TR13',
      question: "Readability: Are long blocks of text avoided?",
      navigate: "Review the Readability evidence within Typography & Readability.",
      options: scaleOptions(),
    },
    {
      id: 'TR14',
      question: "Readability: Are all-caps paragraphs avoided?",
      navigate: "Review the Readability evidence within Typography & Readability.",
      options: scaleOptions(),
    },
    {
      id: 'TR15',
      question: "Readability: Are complex sentence structures simplified?",
      navigate: "Review the Readability evidence within Typography & Readability.",
      options: scaleOptions(),
    },
    {
      id: 'TR16',
      question: "Hierarchy: Can users clearly distinguish page titles?",
      navigate: "Review the Hierarchy evidence within Typography & Readability.",
      options: scaleOptions(),
    },
    {
      id: 'TR17',
      question: "Hierarchy: Can users distinguish headings and subheadings?",
      navigate: "Review the Hierarchy evidence within Typography & Readability.",
      options: scaleOptions(),
    },
    {
      id: 'TR18',
      question: "Hierarchy: Is body text visually different from supporting text?",
      navigate: "Review the Hierarchy evidence within Typography & Readability.",
      options: scaleOptions(),
    },
    {
      id: 'TR19',
      question: "Hierarchy: Are labels and instructions clearly differentiated?",
      navigate: "Review the Hierarchy evidence within Typography & Readability.",
      options: scaleOptions(),
    },
    {
      id: 'TR20',
      question: "Hierarchy: Does the visual hierarchy match the semantic heading structure?",
      navigate: "Review the Hierarchy evidence within Typography & Readability.",
      options: scaleOptions(),
    },
    {
      id: 'TR21',
      question: "Hierarchy: Can users quickly identify the most important information?",
      navigate: "Review the Hierarchy evidence within Typography & Readability.",
      options: scaleOptions(),
    },
  ],
  'Keyboard Navigation': [
    {
      id: 'KN01',
      question: "Tab Order: Does focus move in a logical sequence using Tab?",
      navigate: "Review the Tab Order evidence within Keyboard Navigation.",
      options: scaleOptions(),
    },
    {
      id: 'KN02',
      question: "Tab Order: Does Shift+Tab move focus in the correct reverse order?",
      navigate: "Review the Tab Order evidence within Keyboard Navigation.",
      options: scaleOptions(),
    },
    {
      id: 'KN03',
      question: "Tab Order: Does the focus order follow the visual layout?",
      navigate: "Review the Tab Order evidence within Keyboard Navigation.",
      options: scaleOptions(),
    },
    {
      id: 'KN04',
      question: "Tab Order: Does the focus order follow the task sequence?",
      navigate: "Review the Tab Order evidence within Keyboard Navigation.",
      options: scaleOptions(),
    },
    {
      id: 'KN05',
      question: "Tab Order: Does focus move appropriately when a modal or menu opens?",
      navigate: "Review the Tab Order evidence within Keyboard Navigation.",
      options: scaleOptions(),
    },
    {
      id: 'KN06',
      question: "Tab Order: Does focus return to the correct location when a modal closes?",
      navigate: "Review the Tab Order evidence within Keyboard Navigation.",
      options: scaleOptions(),
    },
    {
      id: 'KN07',
      question: "Focus Visibility: Is the currently focused element always clearly visible?",
      navigate: "Review the Focus Visibility evidence within Keyboard Navigation.",
      options: scaleOptions(),
    },
    {
      id: 'KN08',
      question: "Focus Visibility: Is the focus indicator easy to distinguish?",
      navigate: "Review the Focus Visibility evidence within Keyboard Navigation.",
      options: scaleOptions(),
    },
    {
      id: 'KN09',
      question: "Focus Visibility: Does the focus indicator have sufficient contrast?",
      navigate: "Review the Focus Visibility evidence within Keyboard Navigation.",
      options: scaleOptions(),
    },
    {
      id: 'KN10',
      question: "Focus Visibility: Is focus prevented from being hidden behind sticky headers or overlays?",
      navigate: "Review the Focus Visibility evidence within Keyboard Navigation.",
      options: scaleOptions(),
    },
    {
      id: 'KN11',
      question: "Focus Visibility: Is focus visible across all interactive elements?",
      navigate: "Review the Focus Visibility evidence within Keyboard Navigation.",
      options: scaleOptions(),
    },
    {
      id: 'KN12',
      question: "Keyboard Shortcuts: Can all essential actions be completed using only the keyboard?",
      navigate: "Review the Keyboard Shortcuts evidence within Keyboard Navigation.",
      options: scaleOptions(),
    },
    {
      id: 'KN13',
      question: "Keyboard Shortcuts: Are standard keyboard controls supported?",
      navigate: "Review the Keyboard Shortcuts evidence within Keyboard Navigation.",
      options: scaleOptions(),
    },
    {
      id: 'KN14',
      question: "Keyboard Shortcuts: Are custom shortcuts documented?",
      navigate: "Review the Keyboard Shortcuts evidence within Keyboard Navigation.",
      options: scaleOptions(),
    },
    {
      id: 'KN15',
      question: "Keyboard Shortcuts: Do shortcuts avoid conflicts with browser or assistive-technology commands?",
      navigate: "Review the Keyboard Shortcuts evidence within Keyboard Navigation.",
      options: scaleOptions(),
    },
    {
      id: 'KN16',
      question: "Keyboard Shortcuts: Can users disable or remap custom shortcuts where necessary?",
      navigate: "Review the Keyboard Shortcuts evidence within Keyboard Navigation.",
      options: scaleOptions(),
    },
    {
      id: 'KN17',
      question: "No Keyboard Traps: Can users enter and exit every interactive component using the keyboard?",
      navigate: "Review the No Keyboard Traps evidence within Keyboard Navigation.",
      options: scaleOptions(),
    },
    {
      id: 'KN18',
      question: "No Keyboard Traps: Can users exit modals using the keyboard?",
      navigate: "Review the No Keyboard Traps evidence within Keyboard Navigation.",
      options: scaleOptions(),
    },
    {
      id: 'KN19',
      question: "No Keyboard Traps: Can users navigate through menus, editors and embedded content?",
      navigate: "Review the No Keyboard Traps evidence within Keyboard Navigation.",
      options: scaleOptions(),
    },
    {
      id: 'KN20',
      question: "No Keyboard Traps: Is focus intentionally contained only when required?",
      navigate: "Review the No Keyboard Traps evidence within Keyboard Navigation.",
      options: scaleOptions(),
    },
    {
      id: 'KN21',
      question: "No Keyboard Traps: Can users always return to the main page content?",
      navigate: "Review the No Keyboard Traps evidence within Keyboard Navigation.",
      options: scaleOptions(),
    },
  ],
  'Screen Reader Support': [
    {
      id: 'SR01',
      question: "Semantic Structure: Are headings implemented using the correct heading elements?",
      navigate: "Review the Semantic Structure evidence within Screen Reader Support.",
      options: scaleOptions(),
    },
    {
      id: 'SR02',
      question: "Semantic Structure: Are landmarks used correctly?",
      navigate: "Review the Semantic Structure evidence within Screen Reader Support.",
      options: scaleOptions(),
    },
    {
      id: 'SR03',
      question: "Semantic Structure: Are lists implemented as lists?",
      navigate: "Review the Semantic Structure evidence within Screen Reader Support.",
      options: scaleOptions(),
    },
    {
      id: 'SR04',
      question: "Semantic Structure: Are data tables structured correctly?",
      navigate: "Review the Semantic Structure evidence within Screen Reader Support.",
      options: scaleOptions(),
    },
    {
      id: 'SR05',
      question: "Semantic Structure: Are buttons implemented as buttons?",
      navigate: "Review the Semantic Structure evidence within Screen Reader Support.",
      options: scaleOptions(),
    },
    {
      id: 'SR06',
      question: "Semantic Structure: Are links implemented as links?",
      navigate: "Review the Semantic Structure evidence within Screen Reader Support.",
      options: scaleOptions(),
    },
    {
      id: 'SR07',
      question: "Semantic Structure: Are form controls implemented using appropriate semantic elements?",
      navigate: "Review the Semantic Structure evidence within Screen Reader Support.",
      options: scaleOptions(),
    },
    {
      id: 'SR08',
      question: "Semantic Structure: Does the screen-reader reading order match the visual order?",
      navigate: "Review the Semantic Structure evidence within Screen Reader Support.",
      options: scaleOptions(),
    },
    {
      id: 'SR09',
      question: "Alt Text: Do informative images have meaningful alternative text?",
      navigate: "Review the Alt Text evidence within Screen Reader Support.",
      options: scaleOptions(),
    },
    {
      id: 'SR10',
      question: "Alt Text: Is alt text concise and relevant?",
      navigate: "Review the Alt Text evidence within Screen Reader Support.",
      options: scaleOptions(),
    },
    {
      id: 'SR11',
      question: "Alt Text: Are decorative images ignored by assistive technologies?",
      navigate: "Review the Alt Text evidence within Screen Reader Support.",
      options: scaleOptions(),
    },
    {
      id: 'SR12',
      question: "Alt Text: Do complex images provide longer descriptions?",
      navigate: "Review the Alt Text evidence within Screen Reader Support.",
      options: scaleOptions(),
    },
    {
      id: 'SR13',
      question: "Alt Text: Is equivalent information available for charts and diagrams?",
      navigate: "Review the Alt Text evidence within Screen Reader Support.",
      options: scaleOptions(),
    },
    {
      id: 'SR14',
      question: "Alt Text: Is redundant alt text avoided?",
      navigate: "Review the Alt Text evidence within Screen Reader Support.",
      options: scaleOptions(),
    },
    {
      id: 'SR15',
      question: "ARIA Labels: Do controls without visible text have accurate accessible names?",
      navigate: "Review the ARIA Labels evidence within Screen Reader Support.",
      options: scaleOptions(),
    },
    {
      id: 'SR16',
      question: "ARIA Labels: Do accessible names match visible labels?",
      navigate: "Review the ARIA Labels evidence within Screen Reader Support.",
      options: scaleOptions(),
    },
    {
      id: 'SR17',
      question: "ARIA Labels: Are icon-only buttons properly labelled?",
      navigate: "Review the ARIA Labels evidence within Screen Reader Support.",
      options: scaleOptions(),
    },
    {
      id: 'SR18',
      question: "ARIA Labels: Is ARIA used only when native semantic elements are insufficient?",
      navigate: "Review the ARIA Labels evidence within Screen Reader Support.",
      options: scaleOptions(),
    },
    {
      id: 'SR19',
      question: "ARIA Labels: Are ARIA states and properties updated when the interface changes?",
      navigate: "Review the ARIA Labels evidence within Screen Reader Support.",
      options: scaleOptions(),
    },
    {
      id: 'SR20',
      question: "Accessible Forms: Does every form field have a persistent label?",
      navigate: "Review the Accessible Forms evidence within Screen Reader Support.",
      options: scaleOptions(),
    },
    {
      id: 'SR21',
      question: "Accessible Forms: Is each label programmatically associated with its field?",
      navigate: "Review the Accessible Forms evidence within Screen Reader Support.",
      options: scaleOptions(),
    },
    {
      id: 'SR22',
      question: "Accessible Forms: Are required fields clearly communicated?",
      navigate: "Review the Accessible Forms evidence within Screen Reader Support.",
      options: scaleOptions(),
    },
    {
      id: 'SR23',
      question: "Accessible Forms: Are expected formats explained before input?",
      navigate: "Review the Accessible Forms evidence within Screen Reader Support.",
      options: scaleOptions(),
    },
    {
      id: 'SR24',
      question: "Accessible Forms: Are instructions provided where needed?",
      navigate: "Review the Accessible Forms evidence within Screen Reader Support.",
      options: scaleOptions(),
    },
    {
      id: 'SR25',
      question: "Accessible Forms: Are validation errors linked to the relevant fields?",
      navigate: "Review the Accessible Forms evidence within Screen Reader Support.",
      options: scaleOptions(),
    },
    {
      id: 'SR26',
      question: "Accessible Forms: Are errors announced to screen-reader users?",
      navigate: "Review the Accessible Forms evidence within Screen Reader Support.",
      options: scaleOptions(),
    },
    {
      id: 'SR27',
      question: "Accessible Forms: Does focus move appropriately after submission errors?",
      navigate: "Review the Accessible Forms evidence within Screen Reader Support.",
      options: scaleOptions(),
    },
    {
      id: 'SR28',
      question: "Accessible Forms: Is entered data preserved when an error occurs?",
      navigate: "Review the Accessible Forms evidence within Screen Reader Support.",
      options: scaleOptions(),
    },
  ],
  'Navigation & Findability': [
    {
      id: 'NF01',
      question: "Information Architecture: Are content and functions grouped according to user expectations?",
      navigate: "Review the Information Architecture evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF02',
      question: "Information Architecture: Are categories clear and mutually understandable?",
      navigate: "Review the Information Architecture evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF03',
      question: "Information Architecture: Can users predict where information will be located?",
      navigate: "Review the Information Architecture evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF04',
      question: "Information Architecture: Can users identify where to go to complete primary tasks?",
      navigate: "Review the Information Architecture evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF05',
      question: "Information Architecture: Do tree-testing results show that users choose the correct path?",
      navigate: "Review the Information Architecture evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF06',
      question: "Information Architecture: Is unnecessary depth in the hierarchy avoided?",
      navigate: "Review the Information Architecture evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF07',
      question: "Navigation: Can users reach all important destinations?",
      navigate: "Review the Navigation evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF08',
      question: "Navigation: Are unnecessary steps avoided?",
      navigate: "Review the Navigation evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF09',
      question: "Navigation: Is navigation consistent across pages?",
      navigate: "Review the Navigation evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF10',
      question: "Navigation: Can users clearly identify their current location?",
      navigate: "Review the Navigation evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF11',
      question: "Navigation: Is the primary navigation easy to discover?",
      navigate: "Review the Navigation evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF12',
      question: "Navigation: Are users able to return to previous or higher-level pages easily?",
      navigate: "Review the Navigation evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF13',
      question: "Menu: Are menu labels clear and understandable?",
      navigate: "Review the Menu evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF14',
      question: "Menu: Are menu labels distinct from one another?",
      navigate: "Review the Menu evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF15',
      question: "Menu: Are labels based on user tasks and terminology?",
      navigate: "Review the Menu evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF16',
      question: "Menu: Are important destinations easy to find?",
      navigate: "Review the Menu evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF17',
      question: "Menu: Is excessive menu nesting avoided?",
      navigate: "Review the Menu evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF18',
      question: "Menu: Does the menu work properly across different screen sizes?",
      navigate: "Review the Menu evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF19',
      question: "Menu: Is the menu accessible through mouse, touch and keyboard?",
      navigate: "Review the Menu evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF20',
      question: "Search: Does search return relevant results for common keywords?",
      navigate: "Review the Search evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF21',
      question: "Search: Does it support alternate terms and synonyms?",
      navigate: "Review the Search evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF22',
      question: "Search: Does it handle minor spelling errors?",
      navigate: "Review the Search evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF23',
      question: "Search: Can users filter results?",
      navigate: "Review the Search evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF24',
      question: "Search: Can users sort results?",
      navigate: "Review the Search evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF25',
      question: "Search: Are search results easy to understand?",
      navigate: "Review the Search evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF26',
      question: "Search: Can users recover from a zero-results state?",
      navigate: "Review the Search evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF27',
      question: "Search: Are useful suggestions shown when no results are found?",
      navigate: "Review the Search evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF28',
      question: "Search: Can users understand why specific results were returned?",
      navigate: "Review the Search evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF29',
      question: "Breadcrumbs: Do breadcrumbs accurately represent the site hierarchy?",
      navigate: "Review the Breadcrumbs evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF30',
      question: "Breadcrumbs: Are parent levels clickable?",
      navigate: "Review the Breadcrumbs evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF31',
      question: "Breadcrumbs: Are breadcrumb labels understandable?",
      navigate: "Review the Breadcrumbs evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF32',
      question: "Breadcrumbs: Is the current page clearly identified?",
      navigate: "Review the Breadcrumbs evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF33',
      question: "Breadcrumbs: Are breadcrumbs shown consistently where needed?",
      navigate: "Review the Breadcrumbs evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF34',
      question: "Breadcrumbs: Do breadcrumbs help users navigate back to higher levels?",
      navigate: "Review the Breadcrumbs evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
  ],
  'Consistency & UI Patterns': [
    {
      id: 'CP01',
      question: "Reusable Components: Are components with the same purpose designed consistently?",
      navigate: "Review the Reusable Components evidence within Consistency & UI Patterns.",
      options: scaleOptions(),
    },
    {
      id: 'CP02',
      question: "Reusable Components: Do repeated components behave consistently?",
      navigate: "Review the Reusable Components evidence within Consistency & UI Patterns.",
      options: scaleOptions(),
    },
    {
      id: 'CP03',
      question: "Reusable Components: Are approved reusable components used across screens?",
      navigate: "Review the Reusable Components evidence within Consistency & UI Patterns.",
      options: scaleOptions(),
    },
    {
      id: 'CP04',
      question: "Reusable Components: Are unnecessary one-off components avoided?",
      navigate: "Review the Reusable Components evidence within Consistency & UI Patterns.",
      options: scaleOptions(),
    },
    {
      id: 'CP05',
      question: "Reusable Components: What percentage of audited screens use approved components?",
      navigate: "Review the Reusable Components evidence within Consistency & UI Patterns.",
      options: scaleOptions(),
    },
    {
      id: 'CP06',
      question: "Reusable Components: Are component variations documented?",
      navigate: "Review the Reusable Components evidence within Consistency & UI Patterns.",
      options: scaleOptions(),
    },
    {
      id: 'CP07',
      question: "Consistent Interaction Patterns: Do similar actions behave consistently throughout the product?",
      navigate: "Review the Consistent Interaction Patterns evidence within Consistency & UI Patterns.",
      options: scaleOptions(),
    },
    {
      id: 'CP08',
      question: "Consistent Interaction Patterns: Does Save work consistently across screens?",
      navigate: "Review the Consistent Interaction Patterns evidence within Consistency & UI Patterns.",
      options: scaleOptions(),
    },
    {
      id: 'CP09',
      question: "Consistent Interaction Patterns: Does Delete follow the same pattern everywhere?",
      navigate: "Review the Consistent Interaction Patterns evidence within Consistency & UI Patterns.",
      options: scaleOptions(),
    },
    {
      id: 'CP10',
      question: "Consistent Interaction Patterns: Are filtering and sorting interactions consistent?",
      navigate: "Review the Consistent Interaction Patterns evidence within Consistency & UI Patterns.",
      options: scaleOptions(),
    },
    {
      id: 'CP11',
      question: "Consistent Interaction Patterns: Do Close and Back actions behave predictably?",
      navigate: "Review the Consistent Interaction Patterns evidence within Consistency & UI Patterns.",
      options: scaleOptions(),
    },
    {
      id: 'CP12',
      question: "Consistent Interaction Patterns: Are confirmation patterns consistent?",
      navigate: "Review the Consistent Interaction Patterns evidence within Consistency & UI Patterns.",
      options: scaleOptions(),
    },
    {
      id: 'CP13',
      question: "Consistent Interaction Patterns: Are users able to predict the result of an interaction?",
      navigate: "Review the Consistent Interaction Patterns evidence within Consistency & UI Patterns.",
      options: scaleOptions(),
    },
    {
      id: 'CP14',
      question: "Design-System Adherence: Are approved colour tokens used?",
      navigate: "Review the Design-System Adherence evidence within Consistency & UI Patterns.",
      options: scaleOptions(),
    },
    {
      id: 'CP15',
      question: "Design-System Adherence: Are approved typography styles used?",
      navigate: "Review the Design-System Adherence evidence within Consistency & UI Patterns.",
      options: scaleOptions(),
    },
    {
      id: 'CP16',
      question: "Design-System Adherence: Are spacing values taken from the design system?",
      navigate: "Review the Design-System Adherence evidence within Consistency & UI Patterns.",
      options: scaleOptions(),
    },
    {
      id: 'CP17',
      question: "Design-System Adherence: Are approved icons and components used?",
      navigate: "Review the Design-System Adherence evidence within Consistency & UI Patterns.",
      options: scaleOptions(),
    },
    {
      id: 'CP18',
      question: "Design-System Adherence: What percentage of the interface follows design-system standards?",
      navigate: "Review the Design-System Adherence evidence within Consistency & UI Patterns.",
      options: scaleOptions(),
    },
    {
      id: 'CP19',
      question: "Design-System Adherence: Are deviations documented?",
      navigate: "Review the Design-System Adherence evidence within Consistency & UI Patterns.",
      options: scaleOptions(),
    },
    {
      id: 'CP20',
      question: "Design-System Adherence: Are deviations justified by a valid product requirement?",
      navigate: "Review the Design-System Adherence evidence within Consistency & UI Patterns.",
      options: scaleOptions(),
    },
  ],
  'Content (Impact)': [
    {
      id: 'CI01',
      question: "Information Correctness: Is displayed information accurate?",
      navigate: "Review the Information Correctness evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI02',
      question: "Information Correctness: Is the information current?",
      navigate: "Review the Information Correctness evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI03',
      question: "Information Correctness: Is content consistent with the approved source of truth?",
      navigate: "Review the Information Correctness evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI04',
      question: "Information Correctness: Are contradictory values absent?",
      navigate: "Review the Information Correctness evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI05',
      question: "Information Correctness: Is outdated information removed?",
      navigate: "Review the Information Correctness evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI06',
      question: "Information Correctness: Are broken references or links absent?",
      navigate: "Review the Information Correctness evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI07',
      question: "Information Correctness: Are dates, prices, names and other key details correct?",
      navigate: "Review the Information Correctness evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI08',
      question: "UX Writing: Are navigation labels clear?",
      navigate: "Review the UX Writing evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI09',
      question: "UX Writing: Are button labels concise and action-oriented?",
      navigate: "Review the UX Writing evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI10',
      question: "UX Writing: Do buttons accurately describe what will happen?",
      navigate: "Review the UX Writing evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI11',
      question: "UX Writing: Are form instructions easy to understand?",
      navigate: "Review the UX Writing evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI12',
      question: "UX Writing: Do error messages explain the problem?",
      navigate: "Review the UX Writing evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI13',
      question: "UX Writing: Do error messages tell users how to recover?",
      navigate: "Review the UX Writing evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI14',
      question: "UX Writing: Do confirmation messages clearly state what was completed?",
      navigate: "Review the UX Writing evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI15',
      question: "UX Writing: Is terminology consistent throughout the product?",
      navigate: "Review the UX Writing evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI16',
      question: "Content Clarity: Can representative users understand the content without explanation?",
      navigate: "Review the Content Clarity evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI17',
      question: "Content Clarity: Are unfamiliar terms defined?",
      navigate: "Review the Content Clarity evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI18',
      question: "Content Clarity: Are instructions specific?",
      navigate: "Review the Content Clarity evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI19',
      question: "Content Clarity: Is unnecessary technical language avoided?",
      navigate: "Review the Content Clarity evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI20',
      question: "Content Clarity: Are important limitations communicated before users commit?",
      navigate: "Review the Content Clarity evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI21',
      question: "Content Clarity: Is the content written in plain language?",
      navigate: "Review the Content Clarity evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI22',
      question: "Content Clarity: Is each message relevant to the current task?",
      navigate: "Review the Content Clarity evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI23',
      question: "Content Hierarchy: Is the most important information shown first?",
      navigate: "Review the Content Hierarchy evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI24',
      question: "Content Hierarchy: Can users quickly understand the purpose of the page?",
      navigate: "Review the Content Hierarchy evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI25',
      question: "Content Hierarchy: Is the primary action easy to identify?",
      navigate: "Review the Content Hierarchy evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI26',
      question: "Content Hierarchy: Is supporting information visually secondary?",
      navigate: "Review the Content Hierarchy evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI27',
      question: "Content Hierarchy: Can users scan the page and find key information quickly?",
      navigate: "Review the Content Hierarchy evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI28',
      question: "Content Hierarchy: Is secondary detail progressively disclosed where appropriate?",
      navigate: "Review the Content Hierarchy evidence within Content (Impact).",
      options: scaleOptions(),
    },
  ],
  'Performance': [
    {
      id: 'PE01',
      question: "Code Performance: Are unnecessary scripts avoided?",
      navigate: "Review the Code Performance evidence within Performance.",
      options: scaleOptions(),
    },
    {
      id: 'PE02',
      question: "Code Performance: Are large assets optimised?",
      navigate: "Review the Code Performance evidence within Performance.",
      options: scaleOptions(),
    },
    {
      id: 'PE03',
      question: "Code Performance: Are unnecessary third-party dependencies removed?",
      navigate: "Review the Code Performance evidence within Performance.",
      options: scaleOptions(),
    },
    {
      id: 'PE04',
      question: "Code Performance: Are console errors absent?",
      navigate: "Review the Code Performance evidence within Performance.",
      options: scaleOptions(),
    },
    {
      id: 'PE05',
      question: "Code Performance: Are repeated or duplicate network requests avoided?",
      navigate: "Review the Code Performance evidence within Performance.",
      options: scaleOptions(),
    },
    {
      id: 'PE06',
      question: "Code Performance: Does the experience perform well on lower-powered devices?",
      navigate: "Review the Code Performance evidence within Performance.",
      options: scaleOptions(),
    },
    {
      id: 'PE07',
      question: "Code Performance: Can users complete key tasks without freezing or crashing?",
      navigate: "Review the Code Performance evidence within Performance.",
      options: scaleOptions(),
    },
    {
      id: 'PE08',
      question: "Load Speed: Does the main content load quickly?",
      navigate: "Review the Load Speed evidence within Performance.",
      options: scaleOptions(),
    },
    {
      id: 'PE09',
      question: "Load Speed: Does it perform well under realistic network conditions?",
      navigate: "Review the Load Speed evidence within Performance.",
      options: scaleOptions(),
    },
    {
      id: 'PE10',
      question: "Load Speed: Is meaningful content displayed before secondary content?",
      navigate: "Review the Load Speed evidence within Performance.",
      options: scaleOptions(),
    },
    {
      id: 'PE11',
      question: "Load Speed: Are images and media optimised?",
      navigate: "Review the Load Speed evidence within Performance.",
      options: scaleOptions(),
    },
    {
      id: 'PE12',
      question: "Load Speed: Are loading states shown while content is being fetched?",
      navigate: "Review the Load Speed evidence within Performance.",
      options: scaleOptions(),
    },
    {
      id: 'PE13',
      question: "Load Speed: Is Largest Contentful Paint within an acceptable range?",
      navigate: "Review the Load Speed evidence within Performance.",
      options: scaleOptions(),
    },
    {
      id: 'PE14',
      question: "Responsiveness: Does the interface respond promptly to clicks?",
      navigate: "Review the Responsiveness evidence within Performance.",
      options: scaleOptions(),
    },
    {
      id: 'PE15',
      question: "Responsiveness: Does typing feel immediate?",
      navigate: "Review the Responsiveness evidence within Performance.",
      options: scaleOptions(),
    },
    {
      id: 'PE16',
      question: "Responsiveness: Does navigation respond without noticeable delay?",
      navigate: "Review the Responsiveness evidence within Performance.",
      options: scaleOptions(),
    },
    {
      id: 'PE17',
      question: "Responsiveness: Are long-running processes communicated clearly?",
      navigate: "Review the Responsiveness evidence within Performance.",
      options: scaleOptions(),
    },
    {
      id: 'PE18',
      question: "Responsiveness: Is Interaction to Next Paint within an acceptable range?",
      navigate: "Review the Responsiveness evidence within Performance.",
      options: scaleOptions(),
    },
    {
      id: 'PE19',
      question: "Responsiveness: Does the interface remain usable during background processing?",
      navigate: "Review the Responsiveness evidence within Performance.",
      options: scaleOptions(),
    },
    {
      id: 'PE20',
      question: "Responsive Layout: Does the experience work correctly on mobile?",
      navigate: "Review the Responsive Layout evidence within Performance.",
      options: scaleOptions(),
    },
    {
      id: 'PE21',
      question: "Responsive Layout: Does it work correctly on tablet?",
      navigate: "Review the Responsive Layout evidence within Performance.",
      options: scaleOptions(),
    },
    {
      id: 'PE22',
      question: "Responsive Layout: Does it work correctly on desktop?",
      navigate: "Review the Responsive Layout evidence within Performance.",
      options: scaleOptions(),
    },
    {
      id: 'PE23',
      question: "Responsive Layout: Is content prevented from clipping or overlapping?",
      navigate: "Review the Responsive Layout evidence within Performance.",
      options: scaleOptions(),
    },
    {
      id: 'PE24',
      question: "Responsive Layout: Is text readable across all supported widths?",
      navigate: "Review the Responsive Layout evidence within Performance.",
      options: scaleOptions(),
    },
    {
      id: 'PE25',
      question: "Responsive Layout: Is unnecessary horizontal scrolling avoided?",
      navigate: "Review the Responsive Layout evidence within Performance.",
      options: scaleOptions(),
    },
    {
      id: 'PE26',
      question: "Responsive Layout: Do components adapt correctly to orientation changes?",
      navigate: "Review the Responsive Layout evidence within Performance.",
      options: scaleOptions(),
    },
  ],
  'Visual Consistency': [
    {
      id: 'VC01',
      question: "Colours: Is the approved colour palette applied consistently?",
      navigate: "Review the Colours evidence within Visual Consistency.",
      options: scaleOptions(),
    },
    {
      id: 'VC02',
      question: "Colours: Do colours maintain the same meaning throughout the product?",
      navigate: "Review the Colours evidence within Visual Consistency.",
      options: scaleOptions(),
    },
    {
      id: 'VC03',
      question: "Colours: Are status colours consistent?",
      navigate: "Review the Colours evidence within Visual Consistency.",
      options: scaleOptions(),
    },
    {
      id: 'VC04',
      question: "Colours: Are unnecessary colour variations avoided?",
      navigate: "Review the Colours evidence within Visual Consistency.",
      options: scaleOptions(),
    },
    {
      id: 'VC05',
      question: "Colours: Are colour treatments consistent across pages and components?",
      navigate: "Review the Colours evidence within Visual Consistency.",
      options: scaleOptions(),
    },
    {
      id: 'VC06',
      question: "Typography: Are font families used consistently?",
      navigate: "Review the Typography evidence within Visual Consistency.",
      options: scaleOptions(),
    },
    {
      id: 'VC07',
      question: "Typography: Are font weights used consistently?",
      navigate: "Review the Typography evidence within Visual Consistency.",
      options: scaleOptions(),
    },
    {
      id: 'VC08',
      question: "Typography: Are font sizes based on a defined type scale?",
      navigate: "Review the Typography evidence within Visual Consistency.",
      options: scaleOptions(),
    },
    {
      id: 'VC09',
      question: "Typography: Are equivalent content types styled consistently?",
      navigate: "Review the Typography evidence within Visual Consistency.",
      options: scaleOptions(),
    },
    {
      id: 'VC10',
      question: "Typography: Are unnecessary typography variations avoided?",
      navigate: "Review the Typography evidence within Visual Consistency.",
      options: scaleOptions(),
    },
    {
      id: 'VC11',
      question: "Spacing: Does the interface follow a defined spacing system?",
      navigate: "Review the Spacing evidence within Visual Consistency.",
      options: scaleOptions(),
    },
    {
      id: 'VC12',
      question: "Spacing: Are margins consistent?",
      navigate: "Review the Spacing evidence within Visual Consistency.",
      options: scaleOptions(),
    },
    {
      id: 'VC13',
      question: "Spacing: Is padding consistent across similar components?",
      navigate: "Review the Spacing evidence within Visual Consistency.",
      options: scaleOptions(),
    },
    {
      id: 'VC14',
      question: "Spacing: Are gaps between related elements consistent?",
      navigate: "Review the Spacing evidence within Visual Consistency.",
      options: scaleOptions(),
    },
    {
      id: 'VC15',
      question: "Spacing: Are alignments visually balanced?",
      navigate: "Review the Spacing evidence within Visual Consistency.",
      options: scaleOptions(),
    },
    {
      id: 'VC16',
      question: "Spacing: Are dense and sparse areas intentionally designed?",
      navigate: "Review the Spacing evidence within Visual Consistency.",
      options: scaleOptions(),
    },
    {
      id: 'VC17',
      question: "Components: Do repeated components maintain the same shape?",
      navigate: "Review the Components evidence within Visual Consistency.",
      options: scaleOptions(),
    },
    {
      id: 'VC18',
      question: "Components: Are component sizes consistent?",
      navigate: "Review the Components evidence within Visual Consistency.",
      options: scaleOptions(),
    },
    {
      id: 'VC19',
      question: "Components: Are styling and behaviour consistent?",
      navigate: "Review the Components evidence within Visual Consistency.",
      options: scaleOptions(),
    },
    {
      id: 'VC20',
      question: "Components: Are component states visually consistent?",
      navigate: "Review the Components evidence within Visual Consistency.",
      options: scaleOptions(),
    },
    {
      id: 'VC21',
      question: "Components: Are unnecessary visual variations avoided?",
      navigate: "Review the Components evidence within Visual Consistency.",
      options: scaleOptions(),
    },
  ],
  'Motion & Microinteractions': [
    {
      id: 'MM01',
      question: "Animations: Does each animation serve a clear purpose?",
      navigate: "Review the Animations evidence within Motion & Microinteractions.",
      options: scaleOptions(),
    },
    {
      id: 'MM02',
      question: "Animations: Does animation communicate status, hierarchy or causality?",
      navigate: "Review the Animations evidence within Motion & Microinteractions.",
      options: scaleOptions(),
    },
    {
      id: 'MM03',
      question: "Animations: Does it support the brand personality?",
      navigate: "Review the Animations evidence within Motion & Microinteractions.",
      options: scaleOptions(),
    },
    {
      id: 'MM04',
      question: "Animations: Is the animation smooth?",
      navigate: "Review the Animations evidence within Motion & Microinteractions.",
      options: scaleOptions(),
    },
    {
      id: 'MM05',
      question: "Animations: Is it non-disruptive?",
      navigate: "Review the Animations evidence within Motion & Microinteractions.",
      options: scaleOptions(),
    },
    {
      id: 'MM06',
      question: "Animations: Does it avoid delaying task completion?",
      navigate: "Review the Animations evidence within Motion & Microinteractions.",
      options: scaleOptions(),
    },
    {
      id: 'MM07',
      question: "Animations: Does it respect reduced-motion preferences?",
      navigate: "Review the Animations evidence within Motion & Microinteractions.",
      options: scaleOptions(),
    },
    {
      id: 'MM08',
      question: "Animations: Is unnecessary decorative animation avoided?",
      navigate: "Review the Animations evidence within Motion & Microinteractions.",
      options: scaleOptions(),
    },
    {
      id: 'MM09',
      question: "Transitions: Do transitions help users understand changes between states?",
      navigate: "Review the Transitions evidence within Motion & Microinteractions.",
      options: scaleOptions(),
    },
    {
      id: 'MM10',
      question: "Transitions: Do they support movement between screens or sections?",
      navigate: "Review the Transitions evidence within Motion & Microinteractions.",
      options: scaleOptions(),
    },
    {
      id: 'MM11',
      question: "Transitions: Are transition durations consistent?",
      navigate: "Review the Transitions evidence within Motion & Microinteractions.",
      options: scaleOptions(),
    },
    {
      id: 'MM12',
      question: "Transitions: Is easing consistent across the product?",
      navigate: "Review the Transitions evidence within Motion & Microinteractions.",
      options: scaleOptions(),
    },
    {
      id: 'MM13',
      question: "Transitions: Are transitions fast enough to avoid slowing users down?",
      navigate: "Review the Transitions evidence within Motion & Microinteractions.",
      options: scaleOptions(),
    },
    {
      id: 'MM14',
      question: "Transitions: Are abrupt or confusing state changes avoided?",
      navigate: "Review the Transitions evidence within Motion & Microinteractions.",
      options: scaleOptions(),
    },
    {
      id: 'MM15',
      question: "Interaction Feedback: Does every user action receive immediate feedback?",
      navigate: "Review the Interaction Feedback evidence within Motion & Microinteractions.",
      options: scaleOptions(),
    },
    {
      id: 'MM16',
      question: "Interaction Feedback: Can users tell whether an action was registered?",
      navigate: "Review the Interaction Feedback evidence within Motion & Microinteractions.",
      options: scaleOptions(),
    },
    {
      id: 'MM17',
      question: "Interaction Feedback: Can users tell whether an action is processing?",
      navigate: "Review the Interaction Feedback evidence within Motion & Microinteractions.",
      options: scaleOptions(),
    },
    {
      id: 'MM18',
      question: "Interaction Feedback: Can users tell whether an action succeeded?",
      navigate: "Review the Interaction Feedback evidence within Motion & Microinteractions.",
      options: scaleOptions(),
    },
    {
      id: 'MM19',
      question: "Interaction Feedback: Can users tell whether an action failed?",
      navigate: "Review the Interaction Feedback evidence within Motion & Microinteractions.",
      options: scaleOptions(),
    },
    {
      id: 'MM20',
      question: "Interaction Feedback: Is feedback proportionate to the importance of the action?",
      navigate: "Review the Interaction Feedback evidence within Motion & Microinteractions.",
      options: scaleOptions(),
    },
    {
      id: 'MM21',
      question: "Interaction Feedback: Can users undo actions where appropriate?",
      navigate: "Review the Interaction Feedback evidence within Motion & Microinteractions.",
      options: scaleOptions(),
    },
  ],
  'Content (Delight)': [
    {
      id: 'CD01',
      question: "Tone of Voice: Is the tone consistent across the product?",
      navigate: "Review the Tone of Voice evidence within Content (Delight).",
      options: scaleOptions(),
    },
    {
      id: 'CD02',
      question: "Tone of Voice: Does the tone reflect the brand personality?",
      navigate: "Review the Tone of Voice evidence within Content (Delight).",
      options: scaleOptions(),
    },
    {
      id: 'CD03',
      question: "Tone of Voice: Is the tone appropriate for navigation and onboarding?",
      navigate: "Review the Tone of Voice evidence within Content (Delight).",
      options: scaleOptions(),
    },
    {
      id: 'CD04',
      question: "Tone of Voice: Is it appropriate for forms and instructions?",
      navigate: "Review the Tone of Voice evidence within Content (Delight).",
      options: scaleOptions(),
    },
    {
      id: 'CD05',
      question: "Tone of Voice: Is it respectful during errors or sensitive situations?",
      navigate: "Review the Tone of Voice evidence within Content (Delight).",
      options: scaleOptions(),
    },
    {
      id: 'CD06',
      question: "Tone of Voice: Is it positive without becoming distracting?",
      navigate: "Review the Tone of Voice evidence within Content (Delight).",
      options: scaleOptions(),
    },
    {
      id: 'CD07',
      question: "Tone of Voice: Does the tone adapt appropriately to serious and celebratory contexts?",
      navigate: "Review the Tone of Voice evidence within Content (Delight).",
      options: scaleOptions(),
    },
    {
      id: 'CD08',
      question: "Information Density: Is enough information shown to support user decisions?",
      navigate: "Review the Information Density evidence within Content (Delight).",
      options: scaleOptions(),
    },
    {
      id: 'CD09',
      question: "Information Density: Is unnecessary information removed?",
      navigate: "Review the Information Density evidence within Content (Delight).",
      options: scaleOptions(),
    },
    {
      id: 'CD10',
      question: "Information Density: Is complex information grouped clearly?",
      navigate: "Review the Information Density evidence within Content (Delight).",
      options: scaleOptions(),
    },
    {
      id: 'CD11',
      question: "Information Density: Is whitespace used effectively?",
      navigate: "Review the Information Density evidence within Content (Delight).",
      options: scaleOptions(),
    },
    {
      id: 'CD12',
      question: "Information Density: Is progressive disclosure used where appropriate?",
      navigate: "Review the Information Density evidence within Content (Delight).",
      options: scaleOptions(),
    },
    {
      id: 'CD13',
      question: "Information Density: Are summaries provided for complex sections?",
      navigate: "Review the Information Density evidence within Content (Delight).",
      options: scaleOptions(),
    },
    {
      id: 'CD14',
      question: "Information Density: Does the interface avoid overwhelming users?",
      navigate: "Review the Information Density evidence within Content (Delight).",
      options: scaleOptions(),
    },
  ],
  'Brand Expression': [
    {
      id: 'BE01',
      question: "Brand Personality: Does the interface express the intended brand traits?",
      navigate: "Review the Brand Personality evidence within Brand Expression.",
      options: scaleOptions(),
    },
    {
      id: 'BE02',
      question: "Brand Personality: Is the brand personality reflected through language?",
      navigate: "Review the Brand Personality evidence within Brand Expression.",
      options: scaleOptions(),
    },
    {
      id: 'BE03',
      question: "Brand Personality: Is it reflected through visual design?",
      navigate: "Review the Brand Personality evidence within Brand Expression.",
      options: scaleOptions(),
    },
    {
      id: 'BE04',
      question: "Brand Personality: Is it reflected through imagery and interaction?",
      navigate: "Review the Brand Personality evidence within Brand Expression.",
      options: scaleOptions(),
    },
    {
      id: 'BE05',
      question: "Brand Personality: Can users distinguish the product from generic competitors?",
      navigate: "Review the Brand Personality evidence within Brand Expression.",
      options: scaleOptions(),
    },
    {
      id: 'BE06',
      question: "Brand Personality: Is the brand expression consistent across the experience?",
      navigate: "Review the Brand Personality evidence within Brand Expression.",
      options: scaleOptions(),
    },
    {
      id: 'BE07',
      question: "Emotional Connection: Does the experience create the intended emotional response?",
      navigate: "Review the Emotional Connection evidence within Brand Expression.",
      options: scaleOptions(),
    },
    {
      id: 'BE08',
      question: "Emotional Connection: Does it build trust?",
      navigate: "Review the Emotional Connection evidence within Brand Expression.",
      options: scaleOptions(),
    },
    {
      id: 'BE09',
      question: "Emotional Connection: Does it make users feel confident?",
      navigate: "Review the Emotional Connection evidence within Brand Expression.",
      options: scaleOptions(),
    },
    {
      id: 'BE10',
      question: "Emotional Connection: Does it create warmth, excitement or reassurance where appropriate?",
      navigate: "Review the Emotional Connection evidence within Brand Expression.",
      options: scaleOptions(),
    },
    {
      id: 'BE11',
      question: "Emotional Connection: Do user interviews confirm the intended emotional response?",
      navigate: "Review the Emotional Connection evidence within Brand Expression.",
      options: scaleOptions(),
    },
    {
      id: 'BE12',
      question: "Emotional Connection: Do satisfaction surveys indicate a positive experience?",
      navigate: "Review the Emotional Connection evidence within Brand Expression.",
      options: scaleOptions(),
    },
    {
      id: 'BE13',
      question: "Visual Identity: Is the logo used according to brand guidelines?",
      navigate: "Review the Visual Identity evidence within Brand Expression.",
      options: scaleOptions(),
    },
    {
      id: 'BE14',
      question: "Visual Identity: Are brand colours applied correctly?",
      navigate: "Review the Visual Identity evidence within Brand Expression.",
      options: scaleOptions(),
    },
    {
      id: 'BE15',
      question: "Visual Identity: Is brand typography used consistently?",
      navigate: "Review the Visual Identity evidence within Brand Expression.",
      options: scaleOptions(),
    },
    {
      id: 'BE16',
      question: "Visual Identity: Are imagery and graphic elements aligned with the brand?",
      navigate: "Review the Visual Identity evidence within Brand Expression.",
      options: scaleOptions(),
    },
    {
      id: 'BE17',
      question: "Visual Identity: Are outdated brand assets absent?",
      navigate: "Review the Visual Identity evidence within Brand Expression.",
      options: scaleOptions(),
    },
    {
      id: 'BE18',
      question: "Visual Identity: Are inconsistent brand treatments removed?",
      navigate: "Review the Visual Identity evidence within Brand Expression.",
      options: scaleOptions(),
    },
  ],
  'Icons & Imagery': [
    {
      id: 'II01',
      question: "Icon Consistency: Do icons use a consistent stroke weight?",
      navigate: "Review the Icon Consistency evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II02',
      question: "Icon Consistency: Do they follow the same fill or outline style?",
      navigate: "Review the Icon Consistency evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II03',
      question: "Icon Consistency: Are icon sizes consistent?",
      navigate: "Review the Icon Consistency evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II04',
      question: "Icon Consistency: Do icons use consistent corner treatments?",
      navigate: "Review the Icon Consistency evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II05',
      question: "Icon Consistency: Do icons follow the same visual perspective?",
      navigate: "Review the Icon Consistency evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II06',
      question: "Icon Consistency: Are icons properly aligned?",
      navigate: "Review the Icon Consistency evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II07',
      question: "Icon Consistency: Are unclear icons supported by labels?",
      navigate: "Review the Icon Consistency evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II08',
      question: "Icon Consistency: Is the meaning of each icon understandable?",
      navigate: "Review the Icon Consistency evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II09',
      question: "Illustration Style: Do illustrations follow a cohesive visual language?",
      navigate: "Review the Illustration Style evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II10',
      question: "Illustration Style: Do they support the content or task?",
      navigate: "Review the Illustration Style evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II11',
      question: "Illustration Style: Are illustration colours and proportions consistent?",
      navigate: "Review the Illustration Style evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II12',
      question: "Illustration Style: Are illustrations aligned with the brand?",
      navigate: "Review the Illustration Style evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II13',
      question: "Illustration Style: Are decorative illustrations prevented from distracting users?",
      navigate: "Review the Illustration Style evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II14',
      question: "Illustration Style: Are unnecessary illustrations avoided?",
      navigate: "Review the Illustration Style evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II15',
      question: "Photography: Is the photography relevant to the content?",
      navigate: "Review the Photography evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II16',
      question: "Photography: Is image quality sufficiently high?",
      navigate: "Review the Photography evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II17',
      question: "Photography: Is photography appropriate for the intended audience?",
      navigate: "Review the Photography evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II18',
      question: "Photography: Are crops consistent?",
      navigate: "Review the Photography evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II19',
      question: "Photography: Are subjects and lighting consistent?",
      navigate: "Review the Photography evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II20',
      question: "Photography: Is representation appropriate and inclusive?",
      navigate: "Review the Photography evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II21',
      question: "Photography: Does photography align with the brand identity?",
      navigate: "Review the Photography evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II22',
      question: "Visual Quality: Are all visual assets sharp?",
      navigate: "Review the Visual Quality evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II23',
      question: "Visual Quality: Are images correctly scaled?",
      navigate: "Review the Visual Quality evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II24',
      question: "Visual Quality: Are distorted visuals absent?",
      navigate: "Review the Visual Quality evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II25',
      question: "Visual Quality: Are crops intentional and appropriate?",
      navigate: "Review the Visual Quality evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II26',
      question: "Visual Quality: Is visible compression avoided?",
      navigate: "Review the Visual Quality evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II27',
      question: "Visual Quality: Are backgrounds visually consistent?",
      navigate: "Review the Visual Quality evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II28',
      question: "Visual Quality: Do assets maintain quality across screen sizes?",
      navigate: "Review the Visual Quality evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II29',
      question: "Visual Quality: Do visuals remain sharp on high-density displays?",
      navigate: "Review the Visual Quality evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
  ],
};

export const QUESTION_BANK_VERSION = "2026-08-06";

const LEGACY_BUCKET_ALIASES: Record<string, string> = {
  "Feedback & System States": "Visual Feedback",
  "Accessibility & Inclusivity": "Color & Contrast",
  "Input, Errors & Validation": "Keyboard Navigation",
  "Visual Hierarchy & Layout": "Typography & Readability",
  "Content & UX Writing": "Content (Impact)",
  "code optimisation": "Performance",
};

function normalizeBucketName(bucketName: string) {
  return LEGACY_BUCKET_ALIASES[bucketName] || bucketName;
}

export function getSelectedBucketQuestions(bucketNames: string[]) {
  return bucketNames.reduce<Record<string, BucketQuestion[]>>((acc, bucketName) => {
    const normalizedBucketName = normalizeBucketName(bucketName);
    const questions = QUESTION_BANK[normalizedBucketName];
    if (questions?.length) acc[normalizedBucketName] = questions;
    return acc;
  }, {});
}
