export type BucketOption = { mark: number; text: string };

export type BucketQuestion = {
  id: string;
  section?: string;
  question: string;
  navigate: string;
  options: BucketOption[];
};

function scaleOptions(): BucketOption[] {
  return [
    { mark: 1, text: 'Missing or severe issues — this requirement is not met' },
    { mark: 2, text: 'Major issues — large gaps or significant friction remain' },
    { mark: 3, text: 'Partially met — usable but inconsistent or incomplete' },
    { mark: 4, text: 'Mostly meets — only minor gaps remain' },
    { mark: 5, text: 'Fully meets — clear, strong, and well supported' },
  ];
}

export const QUESTION_BANK: Record<string, BucketQuestion[]> = {
  'Visual Feedback': [
    {
      id: 'VF01',
      section: "Loading States",
      question: "Is feedback shown immediately after an action starts?",
      navigate: "Review the Loading States evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF02',
      section: "Loading States",
      question: "Does the loading state clearly indicate that the system is working?",
      navigate: "Review the Loading States evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF03',
      section: "Loading States",
      question: "Does it prevent users from submitting the same action multiple times?",
      navigate: "Review the Loading States evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF04',
      section: "Loading States",
      question: "Is the loading status communicated to assistive technologies?",
      navigate: "Review the Loading States evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF05',
      section: "Empty States",
      question: "Does the empty state explain why no content is available?",
      navigate: "Review the Empty States evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF06',
      section: "Empty States",
      question: "Does it provide a relevant next action?",
      navigate: "Review the Empty States evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF07',
      section: "Empty States",
      question: "Does it avoid leaving users with a blank or confusing screen?",
      navigate: "Review the Empty States evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF08',
      section: "Success States",
      question: "Does the interface clearly confirm that the action was completed?",
      navigate: "Review the Success States evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF09',
      section: "Success States",
      question: "Does it explain what was successfully completed?",
      navigate: "Review the Success States evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF10',
      section: "Success States",
      question: "Does it communicate whether any further action is required?",
      navigate: "Review the Success States evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF11',
      section: "Success States",
      question: "Is the success message announced to screen-reader users?",
      navigate: "Review the Success States evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF12',
      section: "Progress Indicators",
      question: "Can users understand their current position in a process?",
      navigate: "Review the Progress Indicators evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF13',
      section: "Progress Indicators",
      question: "Are completed steps clearly identified?",
      navigate: "Review the Progress Indicators evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF14',
      section: "Progress Indicators",
      question: "Are the remaining steps or remaining progress visible?",
      navigate: "Review the Progress Indicators evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF15',
      section: "Progress Indicators",
      question: "Is progress communicated both visually and programmatically?",
      navigate: "Review the Progress Indicators evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF16',
      section: "Hover States",
      question: "Do interactive elements provide a clear hover state?",
      navigate: "Review the Hover States evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF17',
      section: "Hover States",
      question: "Is hover avoided as the only way to discover functionality?",
      navigate: "Review the Hover States evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF18',
      section: "Hover States",
      question: "Is hover-triggered information also available through keyboard focus?",
      navigate: "Review the Hover States evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF19',
      section: "Selected States",
      question: "Can users clearly distinguish selected and unselected items?",
      navigate: "Review the Selected States evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF20',
      section: "Selected States",
      question: "Is selection communicated using more than colour alone?",
      navigate: "Review the Selected States evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF21',
      section: "Selected States",
      question: "Is the selected state communicated programmatically?",
      navigate: "Review the Selected States evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF22',
      section: "Active States",
      question: "Does the element visibly respond when clicked, tapped or pressed?",
      navigate: "Review the Active States evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF23',
      section: "Active States",
      question: "Can users distinguish the active state from hover, focus, selected and disabled states?",
      navigate: "Review the Active States evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF24',
      section: "Error States",
      question: "Does the interface clearly identify the exact error?",
      navigate: "Review the Error States evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF25',
      section: "Error States",
      question: "Does it explain why the error occurred?",
      navigate: "Review the Error States evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF26',
      section: "Error States",
      question: "Does it tell users how to correct the error?",
      navigate: "Review the Error States evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF27',
      section: "Error States",
      question: "Is the error communicated using text or an icon in addition to colour?",
      navigate: "Review the Error States evidence within Visual Feedback.",
      options: scaleOptions(),
    },
    {
      id: 'VF28',
      section: "Error States",
      question: "Is the error announced to screen-reader users?",
      navigate: "Review the Error States evidence within Visual Feedback.",
      options: scaleOptions(),
    },
  ],
  'Color & Contrast': [
    {
      id: 'CC01',
      section: "Contrast Ratio",
      question: "Does normal text meet a minimum contrast ratio of 4.5:1?",
      navigate: "Review the Contrast Ratio evidence within Color & Contrast.",
      options: scaleOptions(),
    },
    {
      id: 'CC02',
      section: "Contrast Ratio",
      question: "Does large text meet a minimum contrast ratio of 3:1?",
      navigate: "Review the Contrast Ratio evidence within Color & Contrast.",
      options: scaleOptions(),
    },
    {
      id: 'CC03',
      section: "Contrast Ratio",
      question: "Do meaningful interface components meet a minimum contrast ratio of 3:1?",
      navigate: "Review the Contrast Ratio evidence within Color & Contrast.",
      options: scaleOptions(),
    },
    {
      id: 'CC04',
      section: "Contrast Ratio",
      question: "Do focus indicators have sufficient contrast against adjacent colours?",
      navigate: "Review the Contrast Ratio evidence within Color & Contrast.",
      options: scaleOptions(),
    },
    {
      id: 'CC05',
      section: "Contrast Ratio",
      question: "Is contrast maintained across default, hover, selected, disabled and error states?",
      navigate: "Review the Contrast Ratio evidence within Color & Contrast.",
      options: scaleOptions(),
    },
    {
      id: 'CC06',
      section: "Colour Accessibility",
      question: "Can important content be distinguished under colour-vision-deficiency simulations?",
      navigate: "Review the Colour Accessibility evidence within Color & Contrast.",
      options: scaleOptions(),
    },
    {
      id: 'CC07',
      section: "Colour Accessibility",
      question: "Are foreground and background combinations readable?",
      navigate: "Review the Colour Accessibility evidence within Color & Contrast.",
      options: scaleOptions(),
    },
    {
      id: 'CC08',
      section: "Colour Accessibility",
      question: "Are status colours visually distinguishable?",
      navigate: "Review the Colour Accessibility evidence within Color & Contrast.",
      options: scaleOptions(),
    },
    {
      id: 'CC09',
      section: "Colour Accessibility",
      question: "Are colours used consistently throughout the product?",
      navigate: "Review the Colour Accessibility evidence within Color & Contrast.",
      options: scaleOptions(),
    },
    {
      id: 'CC10',
      section: "Do Not Rely on Colour Alone",
      question: "Are errors supported by text, icons or labels?",
      navigate: "Review the Do Not Rely on Colour Alone evidence within Color & Contrast.",
      options: scaleOptions(),
    },
    {
      id: 'CC11',
      section: "Do Not Rely on Colour Alone",
      question: "Are success states supported by text or icons?",
      navigate: "Review the Do Not Rely on Colour Alone evidence within Color & Contrast.",
      options: scaleOptions(),
    },
    {
      id: 'CC12',
      section: "Do Not Rely on Colour Alone",
      question: "Are selected states communicated through more than colour?",
      navigate: "Review the Do Not Rely on Colour Alone evidence within Color & Contrast.",
      options: scaleOptions(),
    },
    {
      id: 'CC13',
      section: "Do Not Rely on Colour Alone",
      question: "Are required fields identified without relying only on colour?",
      navigate: "Review the Do Not Rely on Colour Alone evidence within Color & Contrast.",
      options: scaleOptions(),
    },
    {
      id: 'CC14',
      section: "Do Not Rely on Colour Alone",
      question: "Do charts use labels, patterns, shapes or legends in addition to colour?",
      navigate: "Review the Do Not Rely on Colour Alone evidence within Color & Contrast.",
      options: scaleOptions(),
    },
  ],
  'Typography & Readability': [
    {
      id: 'TR01',
      section: "Font Size",
      question: "Is body text comfortably readable on desktop?",
      navigate: "Review the Font Size evidence within Typography & Readability.",
      options: scaleOptions(),
    },
    {
      id: 'TR02',
      section: "Font Size",
      question: "Is body text comfortably readable on mobile?",
      navigate: "Review the Font Size evidence within Typography & Readability.",
      options: scaleOptions(),
    },
    {
      id: 'TR03',
      section: "Font Size",
      question: "Can users zoom text to 200% without losing content?",
      navigate: "Review the Font Size evidence within Typography & Readability.",
      options: scaleOptions(),
    },
    {
      id: 'TR04',
      section: "Font Size",
      question: "Does zooming avoid clipping, overlapping or hidden content?",
      navigate: "Review the Font Size evidence within Typography & Readability.",
      options: scaleOptions(),
    },
    {
      id: 'TR05',
      section: "Line Height",
      question: "Is there sufficient vertical spacing between lines?",
      navigate: "Review the Line Height evidence within Typography & Readability.",
      options: scaleOptions(),
    },
    {
      id: 'TR06',
      section: "Line Height",
      question: "Can users comfortably scan paragraphs?",
      navigate: "Review the Line Height evidence within Typography & Readability.",
      options: scaleOptions(),
    },
    {
      id: 'TR07',
      section: "Line Height",
      question: "Does the interface remain usable when line spacing is increased?",
      navigate: "Review the Line Height evidence within Typography & Readability.",
      options: scaleOptions(),
    },
    {
      id: 'TR08',
      section: "Line Height",
      question: "Does it remain usable when letter, word and paragraph spacing are increased?",
      navigate: "Review the Line Height evidence within Typography & Readability.",
      options: scaleOptions(),
    },
    {
      id: 'TR09',
      section: "Readability",
      question: "Are sentences clear and concise?",
      navigate: "Review the Readability evidence within Typography & Readability.",
      options: scaleOptions(),
    },
    {
      id: 'TR10',
      section: "Readability",
      question: "Is familiar and simple language used?",
      navigate: "Review the Readability evidence within Typography & Readability.",
      options: scaleOptions(),
    },
    {
      id: 'TR11',
      section: "Readability",
      question: "Are paragraphs easy to scan?",
      navigate: "Review the Readability evidence within Typography & Readability.",
      options: scaleOptions(),
    },
    {
      id: 'TR12',
      section: "Readability",
      question: "Is unnecessary jargon avoided?",
      navigate: "Review the Readability evidence within Typography & Readability.",
      options: scaleOptions(),
    },
    {
      id: 'TR13',
      section: "Readability",
      question: "Are long blocks of text avoided?",
      navigate: "Review the Readability evidence within Typography & Readability.",
      options: scaleOptions(),
    },
    {
      id: 'TR14',
      section: "Readability",
      question: "Are all-caps paragraphs avoided?",
      navigate: "Review the Readability evidence within Typography & Readability.",
      options: scaleOptions(),
    },
    {
      id: 'TR15',
      section: "Readability",
      question: "Are complex sentence structures simplified?",
      navigate: "Review the Readability evidence within Typography & Readability.",
      options: scaleOptions(),
    },
    {
      id: 'TR16',
      section: "Hierarchy",
      question: "Can users clearly distinguish page titles?",
      navigate: "Review the Hierarchy evidence within Typography & Readability.",
      options: scaleOptions(),
    },
    {
      id: 'TR17',
      section: "Hierarchy",
      question: "Can users distinguish headings and subheadings?",
      navigate: "Review the Hierarchy evidence within Typography & Readability.",
      options: scaleOptions(),
    },
    {
      id: 'TR18',
      section: "Hierarchy",
      question: "Is body text visually different from supporting text?",
      navigate: "Review the Hierarchy evidence within Typography & Readability.",
      options: scaleOptions(),
    },
    {
      id: 'TR19',
      section: "Hierarchy",
      question: "Are labels and instructions clearly differentiated?",
      navigate: "Review the Hierarchy evidence within Typography & Readability.",
      options: scaleOptions(),
    },
    {
      id: 'TR20',
      section: "Hierarchy",
      question: "Does the visual hierarchy match the semantic heading structure?",
      navigate: "Review the Hierarchy evidence within Typography & Readability.",
      options: scaleOptions(),
    },
    {
      id: 'TR21',
      section: "Hierarchy",
      question: "Can users quickly identify the most important information?",
      navigate: "Review the Hierarchy evidence within Typography & Readability.",
      options: scaleOptions(),
    },
  ],
  'Keyboard Navigation': [
    {
      id: 'KN01',
      section: "Tab Order",
      question: "Does focus move in a logical sequence using Tab?",
      navigate: "Review the Tab Order evidence within Keyboard Navigation.",
      options: scaleOptions(),
    },
    {
      id: 'KN02',
      section: "Tab Order",
      question: "Does Shift+Tab move focus in the correct reverse order?",
      navigate: "Review the Tab Order evidence within Keyboard Navigation.",
      options: scaleOptions(),
    },
    {
      id: 'KN03',
      section: "Tab Order",
      question: "Does the focus order follow the visual layout?",
      navigate: "Review the Tab Order evidence within Keyboard Navigation.",
      options: scaleOptions(),
    },
    {
      id: 'KN04',
      section: "Tab Order",
      question: "Does the focus order follow the task sequence?",
      navigate: "Review the Tab Order evidence within Keyboard Navigation.",
      options: scaleOptions(),
    },
    {
      id: 'KN05',
      section: "Tab Order",
      question: "Does focus move appropriately when a modal or menu opens?",
      navigate: "Review the Tab Order evidence within Keyboard Navigation.",
      options: scaleOptions(),
    },
    {
      id: 'KN06',
      section: "Tab Order",
      question: "Does focus return to the correct location when a modal closes?",
      navigate: "Review the Tab Order evidence within Keyboard Navigation.",
      options: scaleOptions(),
    },
    {
      id: 'KN07',
      section: "Focus Visibility",
      question: "Is the currently focused element always clearly visible?",
      navigate: "Review the Focus Visibility evidence within Keyboard Navigation.",
      options: scaleOptions(),
    },
    {
      id: 'KN08',
      section: "Focus Visibility",
      question: "Is the focus indicator easy to distinguish?",
      navigate: "Review the Focus Visibility evidence within Keyboard Navigation.",
      options: scaleOptions(),
    },
    {
      id: 'KN09',
      section: "Focus Visibility",
      question: "Does the focus indicator have sufficient contrast?",
      navigate: "Review the Focus Visibility evidence within Keyboard Navigation.",
      options: scaleOptions(),
    },
    {
      id: 'KN10',
      section: "Focus Visibility",
      question: "Is focus prevented from being hidden behind sticky headers or overlays?",
      navigate: "Review the Focus Visibility evidence within Keyboard Navigation.",
      options: scaleOptions(),
    },
    {
      id: 'KN11',
      section: "Focus Visibility",
      question: "Is focus visible across all interactive elements?",
      navigate: "Review the Focus Visibility evidence within Keyboard Navigation.",
      options: scaleOptions(),
    },
    {
      id: 'KN12',
      section: "Keyboard Shortcuts",
      question: "Can all essential actions be completed using only the keyboard?",
      navigate: "Review the Keyboard Shortcuts evidence within Keyboard Navigation.",
      options: scaleOptions(),
    },
    {
      id: 'KN13',
      section: "Keyboard Shortcuts",
      question: "Are standard keyboard controls supported?",
      navigate: "Review the Keyboard Shortcuts evidence within Keyboard Navigation.",
      options: scaleOptions(),
    },
    {
      id: 'KN14',
      section: "Keyboard Shortcuts",
      question: "Are custom shortcuts documented?",
      navigate: "Review the Keyboard Shortcuts evidence within Keyboard Navigation.",
      options: scaleOptions(),
    },
    {
      id: 'KN15',
      section: "Keyboard Shortcuts",
      question: "Do shortcuts avoid conflicts with browser or assistive-technology commands?",
      navigate: "Review the Keyboard Shortcuts evidence within Keyboard Navigation.",
      options: scaleOptions(),
    },
    {
      id: 'KN16',
      section: "Keyboard Shortcuts",
      question: "Can users disable or remap custom shortcuts where necessary?",
      navigate: "Review the Keyboard Shortcuts evidence within Keyboard Navigation.",
      options: scaleOptions(),
    },
    {
      id: 'KN17',
      section: "No Keyboard Traps",
      question: "Can users enter and exit every interactive component using the keyboard?",
      navigate: "Review the No Keyboard Traps evidence within Keyboard Navigation.",
      options: scaleOptions(),
    },
    {
      id: 'KN18',
      section: "No Keyboard Traps",
      question: "Can users exit modals using the keyboard?",
      navigate: "Review the No Keyboard Traps evidence within Keyboard Navigation.",
      options: scaleOptions(),
    },
    {
      id: 'KN19',
      section: "No Keyboard Traps",
      question: "Can users navigate through menus, editors and embedded content?",
      navigate: "Review the No Keyboard Traps evidence within Keyboard Navigation.",
      options: scaleOptions(),
    },
    {
      id: 'KN20',
      section: "No Keyboard Traps",
      question: "Is focus intentionally contained only when required?",
      navigate: "Review the No Keyboard Traps evidence within Keyboard Navigation.",
      options: scaleOptions(),
    },
    {
      id: 'KN21',
      section: "No Keyboard Traps",
      question: "Can users always return to the main page content?",
      navigate: "Review the No Keyboard Traps evidence within Keyboard Navigation.",
      options: scaleOptions(),
    },
  ],
  'Screen Reader Support': [
    {
      id: 'SR01',
      section: "Semantic Structure",
      question: "Are headings and landmarks implemented semantically?",
      navigate: "Review the Semantic Structure evidence within Screen Reader Support.",
      options: scaleOptions(),
    },
    {
      id: 'SR02',
      section: "Semantic Structure",
      question: "Are lists, tables, buttons, and links using native elements?",
      navigate: "Review the Semantic Structure evidence within Screen Reader Support.",
      options: scaleOptions(),
    },
    {
      id: 'SR03',
      section: "Semantic Structure",
      question: "Are form controls built with appropriate semantic elements?",
      navigate: "Review the Semantic Structure evidence within Screen Reader Support.",
      options: scaleOptions(),
    },
    {
      id: 'SR04',
      section: "Semantic Structure",
      question: "Does the screen-reader reading order match the visual order?",
      navigate: "Review the Semantic Structure evidence within Screen Reader Support.",
      options: scaleOptions(),
    },
    {
      id: 'SR05',
      section: "Alt Text",
      question: "Do informative images have meaningful alternative text?",
      navigate: "Review the Alt Text evidence within Screen Reader Support.",
      options: scaleOptions(),
    },
    {
      id: 'SR06',
      section: "Alt Text",
      question: "Are decorative images hidden from assistive technologies?",
      navigate: "Review the Alt Text evidence within Screen Reader Support.",
      options: scaleOptions(),
    },
    {
      id: 'SR07',
      section: "Alt Text",
      question: "Are complex images or charts described with equivalent text?",
      navigate: "Review the Alt Text evidence within Screen Reader Support.",
      options: scaleOptions(),
    },
    {
      id: 'SR08',
      section: "ARIA Labels",
      question: "Do controls without visible text have accurate accessible names?",
      navigate: "Review the ARIA Labels evidence within Screen Reader Support.",
      options: scaleOptions(),
    },
    {
      id: 'SR09',
      section: "ARIA Labels",
      question: "Do accessible names match visible labels?",
      navigate: "Review the ARIA Labels evidence within Screen Reader Support.",
      options: scaleOptions(),
    },
    {
      id: 'SR10',
      section: "Accessible Forms",
      question: "Are errors, state changes, and required fields announced clearly?",
      navigate: "Review the Accessible Forms evidence within Screen Reader Support.",
      options: scaleOptions(),
    },
  ],
  'Navigation & Findability': [
    {
      id: 'NF01',
      section: "Information Architecture",
      question: "Are content and functions grouped according to user expectations?",
      navigate: "Review the Information Architecture evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF02',
      section: "Information Architecture",
      question: "Are categories clear and mutually understandable?",
      navigate: "Review the Information Architecture evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF03',
      section: "Information Architecture",
      question: "Can users predict where information will be located?",
      navigate: "Review the Information Architecture evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF04',
      section: "Information Architecture",
      question: "Can users identify where to go to complete primary tasks?",
      navigate: "Review the Information Architecture evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF05',
      section: "Information Architecture",
      question: "Do tree-testing results show that users choose the correct path?",
      navigate: "Review the Information Architecture evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF06',
      section: "Information Architecture",
      question: "Is unnecessary depth in the hierarchy avoided?",
      navigate: "Review the Information Architecture evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF07',
      section: "Navigation",
      question: "Can users reach all important destinations?",
      navigate: "Review the Navigation evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF08',
      section: "Navigation",
      question: "Are unnecessary steps avoided?",
      navigate: "Review the Navigation evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF09',
      section: "Navigation",
      question: "Is navigation consistent across pages?",
      navigate: "Review the Navigation evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF10',
      section: "Navigation",
      question: "Can users clearly identify their current location?",
      navigate: "Review the Navigation evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF11',
      section: "Navigation",
      question: "Is the primary navigation easy to discover?",
      navigate: "Review the Navigation evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF12',
      section: "Navigation",
      question: "Are users able to return to previous or higher-level pages easily?",
      navigate: "Review the Navigation evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF13',
      section: "Menu",
      question: "Are menu labels clear and understandable?",
      navigate: "Review the Menu evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF14',
      section: "Menu",
      question: "Are menu labels distinct from one another?",
      navigate: "Review the Menu evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF15',
      section: "Menu",
      question: "Are labels based on user tasks and terminology?",
      navigate: "Review the Menu evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF16',
      section: "Menu",
      question: "Are important destinations easy to find?",
      navigate: "Review the Menu evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF17',
      section: "Menu",
      question: "Is excessive menu nesting avoided?",
      navigate: "Review the Menu evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF18',
      section: "Menu",
      question: "Does the menu work properly across different screen sizes?",
      navigate: "Review the Menu evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF19',
      section: "Menu",
      question: "Is the menu accessible through mouse, touch and keyboard?",
      navigate: "Review the Menu evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF20',
      section: "Search",
      question: "Does search return relevant results for common keywords?",
      navigate: "Review the Search evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF21',
      section: "Search",
      question: "Does it support alternate terms and synonyms?",
      navigate: "Review the Search evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF22',
      section: "Search",
      question: "Does it handle minor spelling errors?",
      navigate: "Review the Search evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF23',
      section: "Search",
      question: "Can users filter results?",
      navigate: "Review the Search evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF24',
      section: "Search",
      question: "Can users sort results?",
      navigate: "Review the Search evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF25',
      section: "Search",
      question: "Are search results easy to understand?",
      navigate: "Review the Search evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF26',
      section: "Search",
      question: "Can users recover from a zero-results state?",
      navigate: "Review the Search evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF27',
      section: "Search",
      question: "Are useful suggestions shown when no results are found?",
      navigate: "Review the Search evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF28',
      section: "Search",
      question: "Can users understand why specific results were returned?",
      navigate: "Review the Search evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF29',
      section: "Breadcrumbs",
      question: "Do breadcrumbs accurately represent the site hierarchy?",
      navigate: "Review the Breadcrumbs evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF30',
      section: "Breadcrumbs",
      question: "Are parent levels clickable?",
      navigate: "Review the Breadcrumbs evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF31',
      section: "Breadcrumbs",
      question: "Are breadcrumb labels understandable?",
      navigate: "Review the Breadcrumbs evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF32',
      section: "Breadcrumbs",
      question: "Is the current page clearly identified?",
      navigate: "Review the Breadcrumbs evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF33',
      section: "Breadcrumbs",
      question: "Are breadcrumbs shown consistently where needed?",
      navigate: "Review the Breadcrumbs evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
    {
      id: 'NF34',
      section: "Breadcrumbs",
      question: "Do breadcrumbs help users navigate back to higher levels?",
      navigate: "Review the Breadcrumbs evidence within Navigation & Findability.",
      options: scaleOptions(),
    },
  ],
  'Consistency & UI Patterns': [
    {
      id: 'CP01',
      section: "Reusable Components",
      question: "Are components with the same purpose designed consistently?",
      navigate: "Review the Reusable Components evidence within Consistency & UI Patterns.",
      options: scaleOptions(),
    },
    {
      id: 'CP02',
      section: "Reusable Components",
      question: "Do repeated components behave consistently?",
      navigate: "Review the Reusable Components evidence within Consistency & UI Patterns.",
      options: scaleOptions(),
    },
    {
      id: 'CP03',
      section: "Reusable Components",
      question: "Are approved reusable components used across screens?",
      navigate: "Review the Reusable Components evidence within Consistency & UI Patterns.",
      options: scaleOptions(),
    },
    {
      id: 'CP04',
      section: "Reusable Components",
      question: "Are unnecessary one-off components avoided?",
      navigate: "Review the Reusable Components evidence within Consistency & UI Patterns.",
      options: scaleOptions(),
    },
    {
      id: 'CP05',
      section: "Reusable Components",
      question: "What percentage of audited screens use approved components?",
      navigate: "Review the Reusable Components evidence within Consistency & UI Patterns.",
      options: scaleOptions(),
    },
    {
      id: 'CP06',
      section: "Reusable Components",
      question: "Are component variations documented?",
      navigate: "Review the Reusable Components evidence within Consistency & UI Patterns.",
      options: scaleOptions(),
    },
    {
      id: 'CP07',
      section: "Consistent Interaction Patterns",
      question: "Do similar actions behave consistently throughout the product?",
      navigate: "Review the Consistent Interaction Patterns evidence within Consistency & UI Patterns.",
      options: scaleOptions(),
    },
    {
      id: 'CP08',
      section: "Consistent Interaction Patterns",
      question: "Does Save work consistently across screens?",
      navigate: "Review the Consistent Interaction Patterns evidence within Consistency & UI Patterns.",
      options: scaleOptions(),
    },
    {
      id: 'CP09',
      section: "Consistent Interaction Patterns",
      question: "Does Delete follow the same pattern everywhere?",
      navigate: "Review the Consistent Interaction Patterns evidence within Consistency & UI Patterns.",
      options: scaleOptions(),
    },
    {
      id: 'CP10',
      section: "Consistent Interaction Patterns",
      question: "Are filtering and sorting interactions consistent?",
      navigate: "Review the Consistent Interaction Patterns evidence within Consistency & UI Patterns.",
      options: scaleOptions(),
    },
    {
      id: 'CP11',
      section: "Consistent Interaction Patterns",
      question: "Do Close and Back actions behave predictably?",
      navigate: "Review the Consistent Interaction Patterns evidence within Consistency & UI Patterns.",
      options: scaleOptions(),
    },
    {
      id: 'CP12',
      section: "Consistent Interaction Patterns",
      question: "Are confirmation patterns consistent?",
      navigate: "Review the Consistent Interaction Patterns evidence within Consistency & UI Patterns.",
      options: scaleOptions(),
    },
    {
      id: 'CP13',
      section: "Consistent Interaction Patterns",
      question: "Are users able to predict the result of an interaction?",
      navigate: "Review the Consistent Interaction Patterns evidence within Consistency & UI Patterns.",
      options: scaleOptions(),
    },
    {
      id: 'CP14',
      section: "Design-System Adherence",
      question: "Are approved colour tokens used?",
      navigate: "Review the Design-System Adherence evidence within Consistency & UI Patterns.",
      options: scaleOptions(),
    },
    {
      id: 'CP15',
      section: "Design-System Adherence",
      question: "Are approved typography styles used?",
      navigate: "Review the Design-System Adherence evidence within Consistency & UI Patterns.",
      options: scaleOptions(),
    },
    {
      id: 'CP16',
      section: "Design-System Adherence",
      question: "Are spacing values taken from the design system?",
      navigate: "Review the Design-System Adherence evidence within Consistency & UI Patterns.",
      options: scaleOptions(),
    },
    {
      id: 'CP17',
      section: "Design-System Adherence",
      question: "Are approved icons and components used?",
      navigate: "Review the Design-System Adherence evidence within Consistency & UI Patterns.",
      options: scaleOptions(),
    },
    {
      id: 'CP18',
      section: "Design-System Adherence",
      question: "What percentage of the interface follows design-system standards?",
      navigate: "Review the Design-System Adherence evidence within Consistency & UI Patterns.",
      options: scaleOptions(),
    },
    {
      id: 'CP19',
      section: "Design-System Adherence",
      question: "Are deviations documented?",
      navigate: "Review the Design-System Adherence evidence within Consistency & UI Patterns.",
      options: scaleOptions(),
    },
    {
      id: 'CP20',
      section: "Design-System Adherence",
      question: "Are deviations justified by a valid product requirement?",
      navigate: "Review the Design-System Adherence evidence within Consistency & UI Patterns.",
      options: scaleOptions(),
    },
  ],
  'Content (Impact)': [
    {
      id: 'CI01',
      section: "Information Correctness",
      question: "Is displayed information accurate?",
      navigate: "Review the Information Correctness evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI02',
      section: "Information Correctness",
      question: "Is the information current?",
      navigate: "Review the Information Correctness evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI03',
      section: "Information Correctness",
      question: "Is content consistent with the approved source of truth?",
      navigate: "Review the Information Correctness evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI04',
      section: "Information Correctness",
      question: "Are contradictory values absent?",
      navigate: "Review the Information Correctness evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI05',
      section: "Information Correctness",
      question: "Is outdated information removed?",
      navigate: "Review the Information Correctness evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI06',
      section: "Information Correctness",
      question: "Are broken references or links absent?",
      navigate: "Review the Information Correctness evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI07',
      section: "Information Correctness",
      question: "Are dates, prices, names and other key details correct?",
      navigate: "Review the Information Correctness evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI08',
      section: "UX Writing",
      question: "Are navigation labels clear?",
      navigate: "Review the UX Writing evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI09',
      section: "UX Writing",
      question: "Are button labels concise and action-oriented?",
      navigate: "Review the UX Writing evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI10',
      section: "UX Writing",
      question: "Do buttons accurately describe what will happen?",
      navigate: "Review the UX Writing evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI11',
      section: "UX Writing",
      question: "Are form instructions easy to understand?",
      navigate: "Review the UX Writing evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI12',
      section: "UX Writing",
      question: "Do error messages explain the problem?",
      navigate: "Review the UX Writing evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI13',
      section: "UX Writing",
      question: "Do error messages tell users how to recover?",
      navigate: "Review the UX Writing evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI14',
      section: "UX Writing",
      question: "Do confirmation messages clearly state what was completed?",
      navigate: "Review the UX Writing evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI15',
      section: "UX Writing",
      question: "Is terminology consistent throughout the product?",
      navigate: "Review the UX Writing evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI16',
      section: "Content Clarity",
      question: "Can representative users understand the content without explanation?",
      navigate: "Review the Content Clarity evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI17',
      section: "Content Clarity",
      question: "Are unfamiliar terms defined?",
      navigate: "Review the Content Clarity evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI18',
      section: "Content Clarity",
      question: "Are instructions specific?",
      navigate: "Review the Content Clarity evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI19',
      section: "Content Clarity",
      question: "Is unnecessary technical language avoided?",
      navigate: "Review the Content Clarity evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI20',
      section: "Content Clarity",
      question: "Are important limitations communicated before users commit?",
      navigate: "Review the Content Clarity evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI21',
      section: "Content Clarity",
      question: "Is the content written in plain language?",
      navigate: "Review the Content Clarity evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI22',
      section: "Content Clarity",
      question: "Is each message relevant to the current task?",
      navigate: "Review the Content Clarity evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI23',
      section: "Content Hierarchy",
      question: "Is the most important information shown first?",
      navigate: "Review the Content Hierarchy evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI24',
      section: "Content Hierarchy",
      question: "Can users quickly understand the purpose of the page?",
      navigate: "Review the Content Hierarchy evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI25',
      section: "Content Hierarchy",
      question: "Is the primary action easy to identify?",
      navigate: "Review the Content Hierarchy evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI26',
      section: "Content Hierarchy",
      question: "Is supporting information visually secondary?",
      navigate: "Review the Content Hierarchy evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI27',
      section: "Content Hierarchy",
      question: "Can users scan the page and find key information quickly?",
      navigate: "Review the Content Hierarchy evidence within Content (Impact).",
      options: scaleOptions(),
    },
    {
      id: 'CI28',
      section: "Content Hierarchy",
      question: "Is secondary detail progressively disclosed where appropriate?",
      navigate: "Review the Content Hierarchy evidence within Content (Impact).",
      options: scaleOptions(),
    },
  ],
  'Performance': [
    {
      id: 'PE01',
      section: "Code & Asset Efficiency",
      question: "Are unnecessary scripts and dependencies avoided?",
      navigate: "Review the Code & Asset Efficiency evidence within Performance.",
      options: scaleOptions(),
    },
    {
      id: 'PE02',
      section: "Code & Asset Efficiency",
      question: "Are large images, media, and other assets optimised?",
      navigate: "Review the Code & Asset Efficiency evidence within Performance.",
      options: scaleOptions(),
    },
    {
      id: 'PE03',
      section: "Code & Asset Efficiency",
      question: "Are repeated or duplicate network requests avoided?",
      navigate: "Review the Code & Asset Efficiency evidence within Performance.",
      options: scaleOptions(),
    },
    {
      id: 'PE04',
      section: "Load Speed",
      question: "Does the main content load quickly?",
      navigate: "Review the Load Speed evidence within Performance.",
      options: scaleOptions(),
    },
    {
      id: 'PE05',
      section: "Load Speed",
      question: "Is meaningful content shown before secondary content?",
      navigate: "Review the Load Speed evidence within Performance.",
      options: scaleOptions(),
    },
    {
      id: 'PE06',
      section: "Load Speed",
      question: "Are loading states shown while content is being fetched?",
      navigate: "Review the Load Speed evidence within Performance.",
      options: scaleOptions(),
    },
    {
      id: 'PE07',
      section: "Responsiveness",
      question: "Does the interface respond promptly to clicks and taps?",
      navigate: "Review the Responsiveness evidence within Performance.",
      options: scaleOptions(),
    },
    {
      id: 'PE08',
      section: "Responsiveness",
      question: "Does typing and navigation feel immediate?",
      navigate: "Review the Responsiveness evidence within Performance.",
      options: scaleOptions(),
    },
    {
      id: 'PE09',
      section: "Responsive Layout",
      question: "Does the experience work correctly on mobile and tablet?",
      navigate: "Review the Responsive Layout evidence within Performance.",
      options: scaleOptions(),
    },
    {
      id: 'PE10',
      section: "Responsive Layout",
      question: "Does the layout avoid clipping, overlap, and unnecessary horizontal scrolling?",
      navigate: "Review the Responsive Layout evidence within Performance.",
      options: scaleOptions(),
    },
  ],
  'Visual Consistency': [
    {
      id: 'VC01',
      section: "Colours",
      question: "Is the approved colour palette applied consistently?",
      navigate: "Review the Colours evidence within Visual Consistency.",
      options: scaleOptions(),
    },
    {
      id: 'VC02',
      section: "Colours",
      question: "Do colours maintain the same meaning throughout the product?",
      navigate: "Review the Colours evidence within Visual Consistency.",
      options: scaleOptions(),
    },
    {
      id: 'VC03',
      section: "Colours",
      question: "Are status colours consistent?",
      navigate: "Review the Colours evidence within Visual Consistency.",
      options: scaleOptions(),
    },
    {
      id: 'VC04',
      section: "Colours",
      question: "Are unnecessary colour variations avoided?",
      navigate: "Review the Colours evidence within Visual Consistency.",
      options: scaleOptions(),
    },
    {
      id: 'VC05',
      section: "Colours",
      question: "Are colour treatments consistent across pages and components?",
      navigate: "Review the Colours evidence within Visual Consistency.",
      options: scaleOptions(),
    },
    {
      id: 'VC06',
      section: "Typography",
      question: "Are font families used consistently?",
      navigate: "Review the Typography evidence within Visual Consistency.",
      options: scaleOptions(),
    },
    {
      id: 'VC07',
      section: "Typography",
      question: "Are font weights used consistently?",
      navigate: "Review the Typography evidence within Visual Consistency.",
      options: scaleOptions(),
    },
    {
      id: 'VC08',
      section: "Typography",
      question: "Are font sizes based on a defined type scale?",
      navigate: "Review the Typography evidence within Visual Consistency.",
      options: scaleOptions(),
    },
    {
      id: 'VC09',
      section: "Typography",
      question: "Are equivalent content types styled consistently?",
      navigate: "Review the Typography evidence within Visual Consistency.",
      options: scaleOptions(),
    },
    {
      id: 'VC10',
      section: "Typography",
      question: "Are unnecessary typography variations avoided?",
      navigate: "Review the Typography evidence within Visual Consistency.",
      options: scaleOptions(),
    },
    {
      id: 'VC11',
      section: "Spacing",
      question: "Does the interface follow a defined spacing system?",
      navigate: "Review the Spacing evidence within Visual Consistency.",
      options: scaleOptions(),
    },
    {
      id: 'VC12',
      section: "Spacing",
      question: "Are margins consistent?",
      navigate: "Review the Spacing evidence within Visual Consistency.",
      options: scaleOptions(),
    },
    {
      id: 'VC13',
      section: "Spacing",
      question: "Is padding consistent across similar components?",
      navigate: "Review the Spacing evidence within Visual Consistency.",
      options: scaleOptions(),
    },
    {
      id: 'VC14',
      section: "Spacing",
      question: "Are gaps between related elements consistent?",
      navigate: "Review the Spacing evidence within Visual Consistency.",
      options: scaleOptions(),
    },
    {
      id: 'VC15',
      section: "Spacing",
      question: "Are alignments visually balanced?",
      navigate: "Review the Spacing evidence within Visual Consistency.",
      options: scaleOptions(),
    },
    {
      id: 'VC16',
      section: "Spacing",
      question: "Are dense and sparse areas intentionally designed?",
      navigate: "Review the Spacing evidence within Visual Consistency.",
      options: scaleOptions(),
    },
    {
      id: 'VC17',
      section: "Components",
      question: "Do repeated components maintain the same shape?",
      navigate: "Review the Components evidence within Visual Consistency.",
      options: scaleOptions(),
    },
    {
      id: 'VC18',
      section: "Components",
      question: "Are component sizes consistent?",
      navigate: "Review the Components evidence within Visual Consistency.",
      options: scaleOptions(),
    },
    {
      id: 'VC19',
      section: "Components",
      question: "Are styling and behaviour consistent?",
      navigate: "Review the Components evidence within Visual Consistency.",
      options: scaleOptions(),
    },
    {
      id: 'VC20',
      section: "Components",
      question: "Are component states visually consistent?",
      navigate: "Review the Components evidence within Visual Consistency.",
      options: scaleOptions(),
    },
    {
      id: 'VC21',
      section: "Components",
      question: "Are unnecessary visual variations avoided?",
      navigate: "Review the Components evidence within Visual Consistency.",
      options: scaleOptions(),
    },
  ],
  'Motion & Microinteractions': [
    {
      id: 'MM01',
      section: "Animations",
      question: "Does each animation serve a clear purpose?",
      navigate: "Review the Animations evidence within Motion & Microinteractions.",
      options: scaleOptions(),
    },
    {
      id: 'MM02',
      section: "Animations",
      question: "Does animation communicate status, hierarchy or causality?",
      navigate: "Review the Animations evidence within Motion & Microinteractions.",
      options: scaleOptions(),
    },
    {
      id: 'MM03',
      section: "Animations",
      question: "Does it support the brand personality?",
      navigate: "Review the Animations evidence within Motion & Microinteractions.",
      options: scaleOptions(),
    },
    {
      id: 'MM04',
      section: "Animations",
      question: "Is the animation smooth?",
      navigate: "Review the Animations evidence within Motion & Microinteractions.",
      options: scaleOptions(),
    },
    {
      id: 'MM05',
      section: "Animations",
      question: "Is it non-disruptive?",
      navigate: "Review the Animations evidence within Motion & Microinteractions.",
      options: scaleOptions(),
    },
    {
      id: 'MM06',
      section: "Animations",
      question: "Does it avoid delaying task completion?",
      navigate: "Review the Animations evidence within Motion & Microinteractions.",
      options: scaleOptions(),
    },
    {
      id: 'MM07',
      section: "Animations",
      question: "Does it respect reduced-motion preferences?",
      navigate: "Review the Animations evidence within Motion & Microinteractions.",
      options: scaleOptions(),
    },
    {
      id: 'MM08',
      section: "Animations",
      question: "Is unnecessary decorative animation avoided?",
      navigate: "Review the Animations evidence within Motion & Microinteractions.",
      options: scaleOptions(),
    },
    {
      id: 'MM09',
      section: "Transitions",
      question: "Do transitions help users understand changes between states?",
      navigate: "Review the Transitions evidence within Motion & Microinteractions.",
      options: scaleOptions(),
    },
    {
      id: 'MM10',
      section: "Transitions",
      question: "Do they support movement between screens or sections?",
      navigate: "Review the Transitions evidence within Motion & Microinteractions.",
      options: scaleOptions(),
    },
    {
      id: 'MM11',
      section: "Transitions",
      question: "Are transition durations consistent?",
      navigate: "Review the Transitions evidence within Motion & Microinteractions.",
      options: scaleOptions(),
    },
    {
      id: 'MM12',
      section: "Transitions",
      question: "Is easing consistent across the product?",
      navigate: "Review the Transitions evidence within Motion & Microinteractions.",
      options: scaleOptions(),
    },
    {
      id: 'MM13',
      section: "Transitions",
      question: "Are transitions fast enough to avoid slowing users down?",
      navigate: "Review the Transitions evidence within Motion & Microinteractions.",
      options: scaleOptions(),
    },
    {
      id: 'MM14',
      section: "Transitions",
      question: "Are abrupt or confusing state changes avoided?",
      navigate: "Review the Transitions evidence within Motion & Microinteractions.",
      options: scaleOptions(),
    },
    {
      id: 'MM15',
      section: "Interaction Feedback",
      question: "Does every user action receive immediate feedback?",
      navigate: "Review the Interaction Feedback evidence within Motion & Microinteractions.",
      options: scaleOptions(),
    },
    {
      id: 'MM16',
      section: "Interaction Feedback",
      question: "Can users tell whether an action was registered?",
      navigate: "Review the Interaction Feedback evidence within Motion & Microinteractions.",
      options: scaleOptions(),
    },
    {
      id: 'MM17',
      section: "Interaction Feedback",
      question: "Can users tell whether an action is processing?",
      navigate: "Review the Interaction Feedback evidence within Motion & Microinteractions.",
      options: scaleOptions(),
    },
    {
      id: 'MM18',
      section: "Interaction Feedback",
      question: "Can users tell whether an action succeeded?",
      navigate: "Review the Interaction Feedback evidence within Motion & Microinteractions.",
      options: scaleOptions(),
    },
    {
      id: 'MM19',
      section: "Interaction Feedback",
      question: "Can users tell whether an action failed?",
      navigate: "Review the Interaction Feedback evidence within Motion & Microinteractions.",
      options: scaleOptions(),
    },
    {
      id: 'MM20',
      section: "Interaction Feedback",
      question: "Is feedback proportionate to the importance of the action?",
      navigate: "Review the Interaction Feedback evidence within Motion & Microinteractions.",
      options: scaleOptions(),
    },
    {
      id: 'MM21',
      section: "Interaction Feedback",
      question: "Can users undo actions where appropriate?",
      navigate: "Review the Interaction Feedback evidence within Motion & Microinteractions.",
      options: scaleOptions(),
    },
  ],
  'Content (Delight)': [
    {
      id: 'CD01',
      section: "Tone of Voice",
      question: "Is the tone consistent across the product?",
      navigate: "Review the Tone of Voice evidence within Content (Delight).",
      options: scaleOptions(),
    },
    {
      id: 'CD02',
      section: "Tone of Voice",
      question: "Does the tone reflect the brand personality?",
      navigate: "Review the Tone of Voice evidence within Content (Delight).",
      options: scaleOptions(),
    },
    {
      id: 'CD03',
      section: "Tone of Voice",
      question: "Is the tone appropriate for navigation and onboarding?",
      navigate: "Review the Tone of Voice evidence within Content (Delight).",
      options: scaleOptions(),
    },
    {
      id: 'CD04',
      section: "Tone of Voice",
      question: "Is it appropriate for forms and instructions?",
      navigate: "Review the Tone of Voice evidence within Content (Delight).",
      options: scaleOptions(),
    },
    {
      id: 'CD05',
      section: "Tone of Voice",
      question: "Is it respectful during errors or sensitive situations?",
      navigate: "Review the Tone of Voice evidence within Content (Delight).",
      options: scaleOptions(),
    },
    {
      id: 'CD06',
      section: "Tone of Voice",
      question: "Is it positive without becoming distracting?",
      navigate: "Review the Tone of Voice evidence within Content (Delight).",
      options: scaleOptions(),
    },
    {
      id: 'CD07',
      section: "Tone of Voice",
      question: "Does the tone adapt appropriately to serious and celebratory contexts?",
      navigate: "Review the Tone of Voice evidence within Content (Delight).",
      options: scaleOptions(),
    },
    {
      id: 'CD08',
      section: "Information Density",
      question: "Is enough information shown to support user decisions?",
      navigate: "Review the Information Density evidence within Content (Delight).",
      options: scaleOptions(),
    },
    {
      id: 'CD09',
      section: "Information Density",
      question: "Is unnecessary information removed?",
      navigate: "Review the Information Density evidence within Content (Delight).",
      options: scaleOptions(),
    },
    {
      id: 'CD10',
      section: "Information Density",
      question: "Is complex information grouped clearly?",
      navigate: "Review the Information Density evidence within Content (Delight).",
      options: scaleOptions(),
    },
    {
      id: 'CD11',
      section: "Information Density",
      question: "Is whitespace used effectively?",
      navigate: "Review the Information Density evidence within Content (Delight).",
      options: scaleOptions(),
    },
    {
      id: 'CD12',
      section: "Information Density",
      question: "Is progressive disclosure used where appropriate?",
      navigate: "Review the Information Density evidence within Content (Delight).",
      options: scaleOptions(),
    },
    {
      id: 'CD13',
      section: "Information Density",
      question: "Are summaries provided for complex sections?",
      navigate: "Review the Information Density evidence within Content (Delight).",
      options: scaleOptions(),
    },
    {
      id: 'CD14',
      section: "Information Density",
      question: "Does the interface avoid overwhelming users?",
      navigate: "Review the Information Density evidence within Content (Delight).",
      options: scaleOptions(),
    },
  ],
  'Brand Expression': [
    {
      id: 'BE01',
      section: "Brand Personality",
      question: "Does the interface express the intended brand traits?",
      navigate: "Review the Brand Personality evidence within Brand Expression.",
      options: scaleOptions(),
    },
    {
      id: 'BE02',
      section: "Brand Personality",
      question: "Is the brand personality reflected through language?",
      navigate: "Review the Brand Personality evidence within Brand Expression.",
      options: scaleOptions(),
    },
    {
      id: 'BE03',
      section: "Brand Personality",
      question: "Is it reflected through visual design?",
      navigate: "Review the Brand Personality evidence within Brand Expression.",
      options: scaleOptions(),
    },
    {
      id: 'BE04',
      section: "Brand Personality",
      question: "Is it reflected through imagery and interaction?",
      navigate: "Review the Brand Personality evidence within Brand Expression.",
      options: scaleOptions(),
    },
    {
      id: 'BE05',
      section: "Brand Personality",
      question: "Can users distinguish the product from generic competitors?",
      navigate: "Review the Brand Personality evidence within Brand Expression.",
      options: scaleOptions(),
    },
    {
      id: 'BE06',
      section: "Brand Personality",
      question: "Is the brand expression consistent across the experience?",
      navigate: "Review the Brand Personality evidence within Brand Expression.",
      options: scaleOptions(),
    },
    {
      id: 'BE07',
      section: "Emotional Connection",
      question: "Does the experience create the intended emotional response?",
      navigate: "Review the Emotional Connection evidence within Brand Expression.",
      options: scaleOptions(),
    },
    {
      id: 'BE08',
      section: "Emotional Connection",
      question: "Does it build trust?",
      navigate: "Review the Emotional Connection evidence within Brand Expression.",
      options: scaleOptions(),
    },
    {
      id: 'BE09',
      section: "Emotional Connection",
      question: "Does it make users feel confident?",
      navigate: "Review the Emotional Connection evidence within Brand Expression.",
      options: scaleOptions(),
    },
    {
      id: 'BE10',
      section: "Emotional Connection",
      question: "Does it create warmth, excitement or reassurance where appropriate?",
      navigate: "Review the Emotional Connection evidence within Brand Expression.",
      options: scaleOptions(),
    },
    {
      id: 'BE11',
      section: "Emotional Connection",
      question: "Do user interviews confirm the intended emotional response?",
      navigate: "Review the Emotional Connection evidence within Brand Expression.",
      options: scaleOptions(),
    },
    {
      id: 'BE12',
      section: "Emotional Connection",
      question: "Do satisfaction surveys indicate a positive experience?",
      navigate: "Review the Emotional Connection evidence within Brand Expression.",
      options: scaleOptions(),
    },
    {
      id: 'BE13',
      section: "Visual Identity",
      question: "Is the logo used according to brand guidelines?",
      navigate: "Review the Visual Identity evidence within Brand Expression.",
      options: scaleOptions(),
    },
    {
      id: 'BE14',
      section: "Visual Identity",
      question: "Are brand colours applied correctly?",
      navigate: "Review the Visual Identity evidence within Brand Expression.",
      options: scaleOptions(),
    },
    {
      id: 'BE15',
      section: "Visual Identity",
      question: "Is brand typography used consistently?",
      navigate: "Review the Visual Identity evidence within Brand Expression.",
      options: scaleOptions(),
    },
    {
      id: 'BE16',
      section: "Visual Identity",
      question: "Are imagery and graphic elements aligned with the brand?",
      navigate: "Review the Visual Identity evidence within Brand Expression.",
      options: scaleOptions(),
    },
    {
      id: 'BE17',
      section: "Visual Identity",
      question: "Are outdated brand assets absent?",
      navigate: "Review the Visual Identity evidence within Brand Expression.",
      options: scaleOptions(),
    },
    {
      id: 'BE18',
      section: "Visual Identity",
      question: "Are inconsistent brand treatments removed?",
      navigate: "Review the Visual Identity evidence within Brand Expression.",
      options: scaleOptions(),
    },
  ],
  'Icons & Imagery': [
    {
      id: 'II01',
      section: "Icon Consistency",
      question: "Do icons use a consistent stroke weight?",
      navigate: "Review the Icon Consistency evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II02',
      section: "Icon Consistency",
      question: "Do they follow the same fill or outline style?",
      navigate: "Review the Icon Consistency evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II03',
      section: "Icon Consistency",
      question: "Are icon sizes consistent?",
      navigate: "Review the Icon Consistency evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II04',
      section: "Icon Consistency",
      question: "Do icons use consistent corner treatments?",
      navigate: "Review the Icon Consistency evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II05',
      section: "Icon Consistency",
      question: "Do icons follow the same visual perspective?",
      navigate: "Review the Icon Consistency evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II06',
      section: "Icon Consistency",
      question: "Are icons properly aligned?",
      navigate: "Review the Icon Consistency evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II07',
      section: "Icon Consistency",
      question: "Are unclear icons supported by labels?",
      navigate: "Review the Icon Consistency evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II08',
      section: "Icon Consistency",
      question: "Is the meaning of each icon understandable?",
      navigate: "Review the Icon Consistency evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II09',
      section: "Illustration Style",
      question: "Do illustrations follow a cohesive visual language?",
      navigate: "Review the Illustration Style evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II10',
      section: "Illustration Style",
      question: "Do they support the content or task?",
      navigate: "Review the Illustration Style evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II11',
      section: "Illustration Style",
      question: "Are illustration colours and proportions consistent?",
      navigate: "Review the Illustration Style evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II12',
      section: "Illustration Style",
      question: "Are illustrations aligned with the brand?",
      navigate: "Review the Illustration Style evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II13',
      section: "Illustration Style",
      question: "Are decorative illustrations prevented from distracting users?",
      navigate: "Review the Illustration Style evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II14',
      section: "Illustration Style",
      question: "Are unnecessary illustrations avoided?",
      navigate: "Review the Illustration Style evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II15',
      section: "Photography",
      question: "Is the photography relevant to the content?",
      navigate: "Review the Photography evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II16',
      section: "Photography",
      question: "Is image quality sufficiently high?",
      navigate: "Review the Photography evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II17',
      section: "Photography",
      question: "Is photography appropriate for the intended audience?",
      navigate: "Review the Photography evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II18',
      section: "Photography",
      question: "Are crops consistent?",
      navigate: "Review the Photography evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II19',
      section: "Photography",
      question: "Are subjects and lighting consistent?",
      navigate: "Review the Photography evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II20',
      section: "Photography",
      question: "Is representation appropriate and inclusive?",
      navigate: "Review the Photography evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II21',
      section: "Photography",
      question: "Does photography align with the brand identity?",
      navigate: "Review the Photography evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II22',
      section: "Visual Quality",
      question: "Are all visual assets sharp?",
      navigate: "Review the Visual Quality evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II23',
      section: "Visual Quality",
      question: "Are images correctly scaled?",
      navigate: "Review the Visual Quality evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II24',
      section: "Visual Quality",
      question: "Are distorted visuals absent?",
      navigate: "Review the Visual Quality evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II25',
      section: "Visual Quality",
      question: "Are crops intentional and appropriate?",
      navigate: "Review the Visual Quality evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II26',
      section: "Visual Quality",
      question: "Is visible compression avoided?",
      navigate: "Review the Visual Quality evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II27',
      section: "Visual Quality",
      question: "Are backgrounds visually consistent?",
      navigate: "Review the Visual Quality evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II28',
      section: "Visual Quality",
      question: "Do assets maintain quality across screen sizes?",
      navigate: "Review the Visual Quality evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
    {
      id: 'II29',
      section: "Visual Quality",
      question: "Do visuals remain sharp on high-density displays?",
      navigate: "Review the Visual Quality evidence within Icons & Imagery.",
      options: scaleOptions(),
    },
  ],
};

export const QUESTION_BANK_VERSION = "2026-08-06b";

const LEGACY_BUCKET_ALIASES: Record<string, string> = {
  "Feedback & System States": "Visual Feedback",
  "Accessibility & Inclusivity": "Color & Contrast",
  "Input, Errors & Validation": "Keyboard Navigation",
  "Visual Hierarchy & Layout": "Typography & Readability",
  "Content & UX Writing": "Content (Impact)",
  "code optimisation": "Performance",
};

export function normalizeBucketName(bucketName: string) {
  return LEGACY_BUCKET_ALIASES[bucketName] || bucketName;
}

export function getSelectedBucketQuestions(bucketNames: string[]) {
  return bucketNames.reduce<Record<string, BucketQuestion[]>>((acc, bucketName) => {
    const normalizedBucketName = normalizeBucketName(bucketName);
    const questions = QUESTION_BANK[normalizedBucketName];
    if (questions?.length) acc[normalizedBucketName] = questions;
    return acc;
  }, {});
}
